stops_m = {"U.S. 150 and Dale": "150DALE",
    "U.S. 150 and Dodson": "150DOD",
    "U.S. 150 and University": "150UNI",
    "1st and Armory": "1STARY",
    "1st and Daniel": "1STDAN",
    "1st and Lot E-14": "1STE14",
    "1st and Gregory": "1STGRG",
    "1st and Gerty": "1STGTY",
    "1st and Hazelwood": "1STHZLWD",
    "1st at iHotel": "1STIHOTEL",
    "1st and Lake Park North": "1STLAKEPKN",
    "1st and Lake Park South": "1STLAKEPKS",
    "1st and St. Mary's": "1STSMR",
    "1st and Stadium": "1STSTDM",
    "1st and Windsor": "1STWDSR",
    "2nd and Church": "2NDCHCH",
    "2nd and Hill": "2NDHILL",
    "2nd and Park": "2NDPK",
    "3rd and Daniel": "3RDDAN",
    "4th and Armory": "4THARY",
    "4th and Armory": "4THARY",
    "4th between Kirby and St Marys": "4THBIELFELDT",
    "4th and Bradley": "4THBRAD",
    "4th and Chalmers": "4THCHAL",
    "4th and Chalmers": "4THCHAL",
    "4th and Gregory": "4THGRG",
    "4th and Kirby": "4THKBY",
    "4th and Pennsylvania": "4THPA",
    "4th and Peabody": "4THPDY",
    "4th and St. Mary's": "4THSMR",
    "5th and Bradley": "5THBRAD",
    "5th and Beardsley": "5THBRD",
    "5th and Chalmers": "5THCHAL",
    "5th and Columbia": "5THCLMBA",
    "5th and Eureka": "5THERKA",
    "5th and Grove": "5THGRV",
    "5th and Tremont": "5THTRMNT",
    "5th and Vine": "5THVIN",
    "5th and Washington": "5THWASH",
    "5th and Washington": "5THWASH",
    "6th and Armory": "6THARY",
    "6th and Bradley": "6THBRAD",
    "6th and Chalmers": "6THCHAL",
    "6th and Gregory": "6THGRG",
    "6th and Peabody": "6THPDY",
    "Anderson and Burkwood": "ADRSNBKWD",
    "Anderson and Brighton": "ADRSNBRTN",
    "Anderson and Colorado": "ADRSNCO",
    "Anderson and Eliot": "ADRSNELIOT",
    "Anderson and Evergreen": "ADRSNEVRGN",
    "Anderson and Fairlawn": "ADRSNFRLN",
    "Anderson and Harding": "ADRSNHRDG",
    "Anderson and Mumford": "ADRSNMFRD",
    "Anderson and Michigan": "ADRSNMI",
    "Anderson and Silver": "ADRSNSLVR",
    "Anderson and Sunnycrest": "ADRSNSNYC",
    "Aldi": "ALDI150",
    "Alpine and Bradley": "ALPBRAD",
    "Alpine and Timberline": "ALPTMBLN",
    "Amber and Myra Ridge": "AMBMYRA",
    "Amber and Philo": "AMBPHILO",
    "Ambucs Park": "AMBUC",
    "Anthony at Ameren": "ANTAMRN",
    "Anthony and Campbell": "ANTCMBL",
    "Anthony and Dale": "ANTDALE",
    "Anthony and Dobbins": "ANTDOBB",
    "Anthony Dr. at Goodwill": "ANTGOODWILL",
    "Anthony at Napleton's": "ANTHNYNAP",
    "Anthony and Willow": "ANTHNYWLLW",
    "Anthony and Columbia": "ANTHYCLMBA",
    "Anthony and Dawn": "ANTHYDAWN",
    "Anthony and Dusk": "ANTHYDUSK",
    "Anthony at Rural King": "ANTHYRK",
    "Anthony at Wood Spring Suites": "ANTHYWSS",
    "Anthony and Kankakee": "ANTKANK",
    "Anthony and Mattis": "ANTMATS",
    "Anthony and North Shore": "ANTNSHR",
    "Anthony and Walters": "ANTWTRS",
    "Airport and Highcross": "APTHICRS",
    "ARC": "ARC",
    "Airport and Arlene": "ARPRTARLNE",
    "Airport and Clifton": "ARPRTCLFTN",
    "Airport and Cunningham": "ARPRTCNGHM",
    "Airport and Captiva": "ARPRTCPTVA",
    "Airport and Donald": "ARPRTDNLD",
    "Airport and Fieldcrest": "ARPRTFDCRST",
    "Airport and Landis Farm": "ARPRTLNDSFRM",
    "Airport and Skyline": "ARPRTSKYLN",
    "Airport and Somerset": "ARPRTSMRST",
    "Airport and Willow": "ARPRTWLLW",
    "Armory and Wright": "ARYWRT",
    "Ashton Woods": "ASHTON",
    "Atrium Apts": "ATRIUM",
    "Baytowne and Boardwalk": "BAYBRDWLK",
    "Beech and Romine": "BCHRMN",
    "Broadmoor and Bellamy": "BDMRBLMY",
    "Broadmoor and Crescent": "BDMRCRSNT",
    "Broadmoor and David": "BDMRDVD",
    "Broadmoor and Galen": "BDMRGLN",
    "Broadmoor and Georgetown": "BDMRGTWN",
    "Broadmoor and Lincoln Pl.": "BDMRLCNPL",
    "Broadmoor and Lynwood": "BDMRLNWD",
    "Broadmoor and Lakeside": "BDMRLSDED",
    "Broadmoor and McDonald": "BDMRMCD",
    "Broadmoor and Robert": "BDMRRBT",
    "Broadway and Bailey": "BDWYBLY",
    "Broadway and Country Club": "BDWYCCR",
    "Broadway and Chapin": "BDWYCHPN",
    "Broadway and Crystal Lake": "BDWYCLD",
    "Save A Lot": "BDWYCM",
    "Broadway and Franklin": "BDWYFRKLN",
    "Broadway and Kerr": "BDWYKER",
    "Broadway and Stebbins": "BDWYLST",
    "Broadway and Oakland": "BDWYOKLN",
    "Broadway and Park": "BDWYPK",
    "Broadway and Thompson": "BDWYTPSN",
    "Broadway and University": "BDWYUNI",
    "Big Lots": "BL",
    "Balboa and Prospect": "BLBOAPSPCT",
    "Balboa and Southwest Dr.": "BLBOASWD",
    "Boulder Ridge and Peppermill": "BLDRRDGPPRML",
    "Boulder Ridge and Farley": "BLDRRGFRLY",
    "Bluegrass and Boca Vista": "BLGRSBCAVSTA",
    "Bluegrass and Boulder Ridge": "BLGRSBLDRRDG",
    "Bluegrass and Brookfield": "BLGRSBRKFLD",
    "Bluegrass and Summersage": "BLGRSSMRSG",
    "Bluegrass and Sandstone": "BLGRSSNDSTN",
    "": "BLOM	Bloomington and Mittendorf",
    "Bloomington and Alabama": "BLOMAL",
    "Bloomington and Prospect": "BLOMHD",
    "Bloomington and Hagan": "BLOMHGN",
    "Bloomington and Highland": "BLOMHILND",
    "Bloomington and Louisiana": "BLOMLA",
    "Bloomington and McKinley": "BLOMMCNLY",
    "Bloomington at Pioneer Plaza": "BLOMPNR",
    "Bloomington and Prospect": "BLOMPSPCT",
    "Bloomington and Sunset": "BLOMSNST",
    "Bloomington and Willis": "BLOMWLS",
    "Bonnie Blair and Amy": "BNBLRAMY",
    "Bonnie Blair and Gold Medal": "BNBLRGDMD",
    "Bonnie Blair and Nancy Beth": "BNBLRNNBTH",
    "Bonnie Blair and Sharon": "BNBLRSHRN",
    "Bonnie Blair and Valerie": "BNBLRVLR",
    "Brownfield and Agnes": "BNFLDAGNS",
    "Brownfield and Airport": "BNFLDAPT",
    "Brownfield and Arlene": "BNFLDARL",
    "Brownfield and Clifton": "BNFLDCFTN",
    "Brownfield and Columbia": "BNFLDCLMBA",
    "Brownfield and Johnson": "BNFLDJHN",
    "Brownfield and Mary Lou": "BNFLDML",
    "Brownfield and Perkins": "BNFLDPKNS",
    "Brownfield and Prairieview": "BNFLDPRVW",
    "Brownfield and Sharlyn": "BNFLDSLYN",
    "Bentbrook and Bentbrook Ct": "BNTBRKBBCT",
    "Bentbrook and Cobblefield": "BNTBRKCBLFLD",
    "Bentbrook and Golf Creek": "BNTBRKGLFCRK",
    "Bentbrook and Pinecrest": "BNTBRKPNCRST",
    "Bentbrook and Riverknoll": "BNTBRKRVRKNL",
    "Bentbrook and Staley": "BNTBRKSTLY",
    "Bradley": "BRAD",
    "Bradley and Country Fair Dr.": "BRADCFD",
    "Bradley and Clayton": "BRADCLTN",
    "Bradley and Champaign": "BRADCMI",
    "Bradley and Crispus": "BRADCRPS",
    "Bradley and Carver": "BRADCRVR",
    "Bradley and Duncan": "BRADDNCN",
    "Bradley and Elm": "BRADELM",
    "Bradley and Garden Hills": "BRADGH",
    "Bradley and Hagan": "BRADHGN",
    "Bradley and Hickory": "BRADHKRY",
    "Bradley and James": "BRADJAS",
    "Bradley and Mattis": "BRADMATS",
    "Bradley and McKinley": "BRADMCNLY",
    "Bradley and Neil": "BRADNEIL",
    "Bradley and Prospect": "BRADPSPCT",
    "Bradley and Redwood": "BRADRDWD",
    "Bradley and State": "BRADSTE",
    "Bradley and Walnut": "BRADWLNT",
    "Bradley and Willis": "BRADWLS",
    "BRADWMBG": "BRADWMBG",
    "Bradley and Williamsburg": "BRADWMBG",
    "Bardeen and Toalson": "BRDNTLSN",
    "Boardwalk and Interstate": "BRDWLKINT",
    "Boardwalk and Meijer Dr.": "BRDWLKMJR",
    "Boardwalk and Town Center": "BRDWLKTCB",
    "Brady and High": "BRDYHI",
    "Brittany Trail and Kensington Knoll": "BRTTRLKNTNKNL",
    "Brittany Trail and Mullikin": "BRTTRLMLKN",
    "Brittany Trail and Southford": "BRTTRLSTHFRD",
    "Brittany Trail and Southford Trace W": "BRTTRLSTHFRDTR",
    "Brittany Trail and Staley": "BRTTRLSTLY",
    "Burwash and Woodfield": "BRWSWDFLD",
    "Beslin and Romine": "BSLNRMN",
    "Butzow and Lierman": "BTSLRMN",
    "Carroll at CACC": "CACC",
    "Campus Circle": "CAMPUSCIR",
    "Country Brook": "CB",
    "Cobblefield and Aberdeen": "CBLFDABDN",
    "Cobblefield and Bridge Point Dr": "CBLFLDBDGPT",
    "Cobblefield and Balmoral": "CBLFLDBLML",
    "Cobblefield and Crail": "CBLFLDCRL",
    "Cobblefield and Englewood": "CBLFLDEGLWD",
    "Cobblefield and Glenn Brooke": "CBLFLDGLNBRK",
    "Cobblefield and Inverness": "CBLFLDINV",
    "Colbert Park": "CBRTPK",
    "Country Club Rd. at Apts.": "CCRAPTS",
    "Country Club and Division": "CCRDVSN",
    "Country Club and Golfview": "CCRGFVW",
    "Country Club and Willow": "CCRWLLW",
    "County Satellite Jail": "CCSJ",
    "Central High": "CE",
    "Central High": "CENTRAL",
    "Country Fair": "CF",
    "Country Fair Dr. and Camp": "CFDCAMP",
    "Country Fair Dr. and Church": "CFDCHCH",
    "Country Fair Dr. and Cone": "CFDCONE",
    "Country Fair Dr. at Fluid Events": "CFDFLDEV",
    "Country Fair Dr. and Park": "CFDPK",
    "Country Fair Dr. at R.P. Lumber": "CFDRP",
    "Springfield and Country Fair Dr.": "CFDSPFLD",
    "Social Security": "CFDSSI",
    "Country Fair Dr. and University": "CFDUNI",
    "Country Fair West Entrance": "CFW",
    "Church St.": "CHCH",
    "Church and Busey": "CHCHBUSY",
    "Church and Carson": "CHCHCRSN",
    "Church and Denton": "CHCHDNTN",
    "Church and Draper": "CHCHDRPR",
    "Church and Edwin": "CHCHEDWN",
    "Church and Elm": "CHCHELM",
    "Church and Fair": "CHCHFAIR",
    "Church and Garfield": "CHCHGRFLD",
    "Church and James": "CHCHJAS",
    "Church and Lynn": "CHCHLYN",
    "Church and Mattis": "CHCHMATS",
    "Church and McKinley": "CHCHMCNLY",
    "Church and Miller": "CHCHMLR",
    "Church and Neil": "CHCHNEIL",
    "Church and New": "CHCHNEW",
    "Church and Orchard": "CHCHORCD",
    "Church and Prairie": "CHCHPRRE",
    "Church and Prospect": "CHCHPSPCT",
    "Church and Russell": "CHCHRSL",
    "Church and State": "CHCHSTE",
    "Church and Victor": "CHCHVCTR",
    "Church and Willis": "CHCHWLS",
    "Chemical and Life Sciences": "CHEMLS",
    "Cherry Hills and Applewood": "CHHLAPLWD",
    "Cherry Hills and Coppertree": "CHHLCPRTRE",
    "Cherry Hills and Curtis": "CHHLCTS",
    "Cherry Hills and Lakeview": "CHHLLKVW",
    "Cherry Hills and Pine Valley": "CHHLPNVY",
    "Cherry Hills and Crestridge": "CHHLSCSTRG",
    "Columbia and Betsy Ross": "CLMBABTSYRS",
    "Columbia and Hickory": "CLMBAHKRY",
    "Columbia and Hancock": "CLMBAHNK",
    "Coler and Church": "CLRCHCH",
    "Coler and Fairview": "CLRFRVW",
    "Clayton and Bellerieve": "CLTNBLRV",
    "Clayton and Clearwater": "CLTNCLW",
    "Clayton and Compton": "CLTNCPT",
    "Clayton and Creve Coeur": "CLTNCRVCR",
    "Clayton and Crestview": "CLTNCSV",
    "Clayton and Covington": "CLTNCVT",
    "Clayton and Delmar": "CLTNDLMR",
    "Clayton and Duncan": "CLTNDNCN",
    "Clayton and Higgins": "CLTNHGN",
    "Clayton and Hilltop": "CLTNHLT",
    "Clayton and Heritage": "CLTNHTG",
    "Clayton and High View": "CLTNHV",
    "Clayton and Irvine": "CLTNIRVN",
    "Clayton and Pomona": "CLTNPMNA",
    "Clayton and Rossmoor": "CLTNRSM",
    "Campbell and Aztec": "CMBLAZTEC",
    "Campbell and Comanche": "CMBLCMCHE",
    "Campbell and Curt": "CMBLCRT",
    "Campbell and Dobbins": "CMBLDBNS",
    "Campbell and Queensway": "CMBLQNWAY",
    "Campbell and Roland": "CMBLRLND",
    "Champaign House": "CMIHS",
    "Cunningham and Crystal Lake": "CNHMCLD",
    "Cunningham and Oakland": "CNHMOKLN",
    "Cunningham and Park": "CNHMPK",
    "Cunningham and Perkins": "CNHMPKNS",
    "Cunningham and Thompson": "CNHMTPSN",
    "Convenience Dr. and Market": "CNVMKT",
    "County Market": "COCM",
    "Colorado and Larch": "COLRCH",
    "Copper Ridge and Blackhawk": "CPRRDGBLKHK",
    "Copper Ridge and Copper": "CPRRDGCPR",
    "Copper Ridge and Ironwood": "CPRRDGIRNWD",
    "Copper Ridge and Mullikin": "CPRRDGMLKN",
    "Copper Ridge and Sand": "CPRRDGSND",
    "Cyprus Point and Stillwater Landing": "CPRSPTSTLWTR",
    "Captiva and George": "CPTVAGRG",
    "Captiva and Northwood": "CPTVANRTHWD",
    "Captiva and Sanibel": "CPTVASNBL",
    "Coronado and Dover": "CRNDODVR",
    "Coronado and Ventura": "CRNDOVTRA",
    "Carroll": "CROL",
    "Carrol Fire Department": "CROLFD",
    "Carroll and Kerr": "CROLKER",
    "Crossgate and Charwick": "CRSGTCHWK",
    "Crossgate and Crossgate Ct.": "CRSGTCRSGTCT",
    "Crossgate and Ironwood Ln": "CRSGTIRNWD",
    "Crescent and Greendale": "CRSNTGRNDL",
    "Jefferson Middle School": "CRSNTJMS",
    "Crescent and John": "CRSNTJOHN",
    "Crescent and Lawndale": "CRSNTLWNDL",
    "Crescent and Ola": "CRSNTOLA",
    "Crescent and Parkdale": "CRSNTPKDL",
    "Round Barn Manor": "CRSNTRBM",
    "Crescent and Round Barn": "CRSNTRBR",
    "Crescent and Rodney": "CRSNTROD",
    "Crescent and Sangamon": "CRSNTSANG",
    "Crescent and Southwood": "CRSNTSWD",
    "Crescent and William": "CRSNTWLM",
    "Crestridge and Lakewood": "CRSTRGLKWD",
    "Crestwood and Bradley": "CRSTWDBRAD",
    "Crestwood and Clayton": "CRSTWDCLTN",
    "Crestwood and Edward Hoffman": "CRSTWDEDHFMN",
    "Crestwood and Florence": "CRSTWDFLNC",
    "Crestwood and Katie Lynn": "CRSTWDKTLYN",
    "Crestwood and Ladue": "CRSTWDLDU",
    "Curtis and Wynstone": "CRTSWNSTN",
    "Country Squire Ct.": "CSQRCT",
    "Country Squire and Kinch": "CSQRKNCH",
    "Cottage Grove and Brighton": "CTGRVBRITN",
    "Cottage Grove and California": "CTGRVCA",
    "Cottage Grove and Colorado": "CTGRVCO",
    "Cottage Grove and Crestwood": "CTGRVCRWD",
    "Cottage Grove and Eastern": "CTGRVERN",
    "Cottage Grove and Glenwood Oaks": "CTGRVGNWD",
    "Cottage Grove and Green": "CTGRVGRN",
    "Cottage Grove and Harding": "CTGRVHRDG",
    "Cottage Grove and Illinois": "CTGRVIL",
    "Cottage Grove and Mitchem": "CTGRVMCHM",
    "Cottage Grove and Oregon": "CTGRVOR",
    "Cottage Grove and Penn": "CTGRVPA",
    "Cottage Grove and Philo": "CTGRVPHILO",
    "Cottage Grove and Washington": "CTGRVWASH",
    "Country Bend and Springhill": "CTRYBNDSPGHL",
    "Country Bend and Summerhill": "CTRYBNDSUMHL",
    "Curtis and 1st": "CTS1ST",
    "Curtis and Meadow": "CTSMDW",
    "Curtis Meadow and Brighton": "CTSMDWBRTN",
    "Curtis Meadow and Foxborough": "CTSMDWFXBRGH",
    "Curtis Meadow and Staley": "CTSMDWSTLY",
    "Curtis Rd. at Winfield Village": "CTSWIN",
    "Public Health District": "CUPHD",
    "Coventry and Maynard": "CVTRYMYNRD",
    "Coventry and Roxford": "CVTRYRXFRD",
    "DART": "DART",
    "Devonshire Corporate Center": "DCC",
    "Dodson and Illinois": "DDSNIL",
    "Dodson and Nevada": "DDSNNV",
    "Dodson and Washington": "DDSNWASH",
    "age": "DEPOT",
    "Duncan and Blair": "DNCNBLR",
    "Duncan and Clark": "DNCNCLKRD",
    "Duncan and Clayton": "DNCNCLTN",
    "Duncan and Crossing Ct.": "DNCNCRSNG",
    "Duncan and Crestridge": "DNCNCSTRG",
    "Duncan and Daniel": "DNCNDNL",
    "Duncan and Lager": "DNCNLGR",
    "Duncan and Lawndale": "DNCNLWNDL",
    "Duncan and Meadows West": "DNCNMWW",
    "Duncan and Prairie Meadow": "DNCNPMDW",
    "Duncan and Ridgewood": "DNCNRDGWD",
    "Duncan and Rolling Acres": "DNCNRLACR",
    "Duncan and Sierra": "DNCNSRA",
    "Duncan and Stoneybrook": "DNCNSTNBK",
    "Duncan and Southwood": "DNCNSWOOD",
    "Duncan and Valerie": "DNCNVLR",
    "Duncan and Valleybrook": "DNCNVYBK",
    "Dorner and Peabody": "DNRPDY",
    "Dodson East and Slayback": "DODSLYBK",
    "Development Services Center": "DSC",
    "D.S.C. on Clark": "DSCCLK",
    "Devonshire and Devonshire Ct.": "DVNDVNCT",
    "Devonshire and Lynnwood Dr.": "DVNLNWD",
    "Devonshire and Lakeside": "DVNLSDED",
    "Devonshire and Mayfair": "DVNMYFR",
    "Devonshire and Noel": "DVNNL",
    "Devonshire and Peach": "DVNPCH",
    "Devonshire and Sandpiper": "DVNSNPR",
    "Dover and Balboa": "DVRBLBOA",
    "Lot E-14": "E14",
    "Eastern": "EAST",
    "Eastern and Kerr": "EASTKER",
    "Elm and Park": "ELMPK",
    "Elm and Vine": "ELMVIN",
    "Edison Middle School": "EMS",
    "FAR": "FAR",
    "Fedex on Killarney": "FEDEXA",
    "Florida and Adams": "FLADAMS",
    "Florida and Anderson": "FLADRSN",
    "Florida and Broadway": "FLBRDWY",
    "Florida and Bermuda": "FLBRMD",
    "Florida and Busey": "FLBUSEY",
    "Florida and Carle": "FLCARLE",
    "Florida and Curtiss": "FLCRTS",
    "Florida and Cottage Grove": "FLCTGRV",
    "Fields South and Farhills": "FLDSFRHL",
    "Fieldstone at Horizon Hobby": "FLDSTNHH",
    "Fieldstone at Metritech": "FLDSTNMETRI",
    "Florida and Florida Ct.": "FLFLCT",
    "Florida and Florida Dr.": "FLFLDR",
    "Florida and Grove": "FLGRV",
    "Florida and Hillcrest": "FLHLCRST",
    "Florida and James Cherry": "FLJASCHER",
    "Florida and Kinch": "FLKNCH",
    "Florida and Lincolnwood": "FLLCLNWD",
    "Florida and Lincoln": "FLLNCLN",
    "Florida and Linden": "FLLNDN",
    "Florida and Maple": "FLMPL",
    "Florida and Orchard": "FLOD",
    "Florida and Philo": "FLPHILO",
    "Florida and Pleasant": "FLPLSNT",
    "Florida and Race": "FLRACE",
    "Florida and Rutledge": "FLRTLG",
    "Florida and Smith": "FLSMITH",
    "Sunnycrest Mall": "FLSUN",
    "Florida at Thomas Paine": "FLTOMPAINE",
    "Florida and Vine": "FLVIN",
    "Florida and Wiley": "FLWLY",
    "Fox at Community Elements": "FOXCE",
    "Fox at Christie Clinic": "FOXCHRSTIE",
    "Fox and Devonshire": "FOXDVN",
    "Fox and Knollwood": "FOXKLWD",
    "Fox at Remax": "FOXREMAX",
    "Fox and State": "FOXSTE",
    "Fox at SURS": "FOXSURS",
    "Fox and Windsor": "FOXWDSR",
    "Farber at CERL": "FRBRCERL",
    "Farber and Newton": "FRBRNWTN",
    "Farhills and Staley": "FRHLSTLY",
    "Fairlawn": "FRLN",
    "Fairlawn and Cottage Grove": "FRLNCTGRV",
    "Fairlawn and Eastern": "FRLNERN",
    "Fairlawn and Grant Pl.": "FRLNGRNT",
    "Fairlawn and Patton": "FRLNPTN",
    "Farley and Pebblebrook": "FRLYPBLBRK",
    "Farley and West Ridge": "FRLYWRDG",
    "Fairview and Busey": "FRVWBUSEY",
    "Fairview and Gregory": "FRVWGRG",
    "Fairview and Goodwin": "FRVWGWN",
    "Fairview and Harvey": "FRVWHRVY",
    "Fairview and Lincoln": "FRVWLNCLN",
    "Fairview and Linview": "FRVWLNVW",
    "Foothill and Robert": "FTHLRBT",
    "Ginger Creek": "GC",
    "Goodwin at Ceramics Building": "GDWNCB",
    "Goodwin at Materials Research": "GDWNMRL",
    "George Huff and Race": "GHFRACE",
    "Galen and Devonshire": "GLNDVN",
    "Galen and Harrington": "GLNHRTN",
    "Galen and Newbury": "GLNNWBY",
    "Galen and Plymouth": "GLNPLMT",
    "Galen and Ross": "GLNROSS",
    "Galen and Salisbury": "GLNSLBY",
    "Galen and Sussex": "GLNSSX",
    "Galen and Theodore": "GLNTDR",
    "Galen and Windsor": "GLNWDSR",
    "Galen and Wilshire": "GLNWLSH",
    "Galen and Yorkshire": "GLNYKSH",
    "Butzow at Guardian West": "GRD",
    "Guardian Dr. and Butzow": "GRDBTZ",
    "Gregory and Dorner": "GRGDNR",
    "Gregory at Ikenberry Commons": "GRGIKE",
    "Gregory at Library": "GRGLIB",
    "Gregory at Mumford Hall": "GRGMUM",
    "Green and 2nd": "GRN2ND",
    "Green and 4th": "GRN4TH",
    "Green and 6th": "GRN6TH",
    "Green and Anderson": "GRNADRSN",
    "Green and Birch": "GRNBRCH",
    "Green and Busey": "GRNBUSEY",
    "Green and Cedar": "GRNCDR",
    "Green and Gregory": "GRNGRGST",
    "Green and Grove": "GRNGRV",
    "Green and Goodwin": "GRNGWN",
    "Green and Johnson": "GRNJNSN",
    "Green and Locust": "GRNLCST",
    "Green and Lynn": "GRNLYN",
    "Green and Mathews": "GRNMAT",
    "Green and Maple": "GRNMPL",
    "Green and Neil": "GRNNEIL",
    "Green and Orchard": "GRNORCH",
    "Green and Prairie": "GRNPRRE",
    "Green and Prospect": "GRNPSPCT",
    "Green and Race": "GRNRACE",
    "Green and Randolph": "GRNRNDLF",
    "Green and State": "GRNSTE",
    "Green and Urbana": "GRNUBNA",
    "Green and Webber": "GRNWBR",
    "Green and Wright": "GRNWRT",
    "Goodwin and Church": "GWNCHCH",
    "Goodwin and Clark": "GWNCLK",
    "Goodwin and Gregory": "GWNGRG",
    "Goodwin and Hill": "GWNHIL",
    "Goodwin and Main": "GWNMN",
    "Goodwin and Nevada": "GWNNV",
    "Goodwin and Park": "GWNPK",
    "Holiday Inn": "HDYINN",
    "Hagan and Dennison": "HGNDNSN",
    "Hagan and Pioneer": "HGNPNR",
    "Highcross and Apostalic Life Church": "HICRSALC",
    "Highcross and Bruce Acres": "HICRSBA",
    "Highcross and Nordland": "HICRSNDLD",
    "Halifax and Maynard": "HLFXMYNRD",
    "Hamilton and Betsy Ross": "HMLTNBTSYRS",
    "Hamilton and Jefferson": "HMTNJFSN",
    "Hancock and Hamilton": "HNKHMTN",
    "Hancock and Liberty": "HNKLBRTY",
    "Hunter and Austin": "HNTRASTN",
    "Hunter and Country Squire": "HNTRCSQR",
    "Hunter and Lanore": "HNTRLNR",
    "Steer Place": "HRDGSTP",
    "Harris and Alabama": "HRISAL",
    "Harris and Bloomington": "HRISBLOM",
    "Harris and Bradley": "HRISBRAD",
    "Harris and Beardsley": "HRISBRD",
    "Franklin Middle School": "HRISFMS",
    "Harris and Harvard": "HRISHRVRD",
    "Harris and Louisiana": "HRISLA",
    "Harris and Maple": "HRISMPL",
    "Harris and Sherwood": "HRISSHWD",
    "Heritage Park": "HRTGPK",
    "Hessel and Randolph": "HSLRNDLF",
    "Hazelwood and Oak": "HZLWDOAK",
    "I.E.T.C.": "IETC",
    "I.E.T.C. and Mattis": "IETCMATS",
    "Independent Living": "ILAPTS",
    "Illinois and Broadway": "ILBDWY",
    "Illinois and Glenn": "ILGLN",
    "The Place at 117": "INDIGO",
    "Independence and Betsy Ross": "INDPNCBTSYRS",
    "Interstate and Waterview Way": "INTERSTWW",
    "Interstate and Farber": "INTFRBR",
    "Interstate and Newmark": "INTNWMK",
    "Interstate and Research": "INTRSRCH",
    "Interstate Dr. at Walmart": "INTWALMART",
    "Inverness and Prestwick Pt": "INVPSTWK",
    "Ironwood and Staley": "IRNWDSTLY",
    "Illinois St. Residence Hall": "ISR",
    "Water Survey": "ISWS",
    "Illinois Terminal": "IT",
    "I. T. at Market St.": "ITMKT",
    "Illini Union": "IU",
    "Jefferson and Columbia": "JFSNCLMBA",
    "Jefferson Middle School": "JMS",
    "John and Chicago": "JOHNCHI",
    "John and Dogwood": "JOHNDGWD",
    "John and Duncan": "JOHNDNCN",
    "John and Draper": "JOHNDRPR",
    "John and Edwin": "JOHNEDWN",
    "John and Elm": "JOHNELM",
    "John and Fair": "JOHNFAIR",
    "John and Foley": "JOHNFOLY",
    "John and Frank": "JOHNFRANK",
    "John and Goldenview": "JOHNGLDVW",
    "John and Garfield": "JOHNGRFLD",
    "John and Highland": "JOHNHILND",
    "John and Hollycrest": "JOHNHLYCST",
    "John and James": "JOHNJAS",
    "John and Kenwood": "JOHNKNWD",
    "John and Lynn": "JOHNLYN",
    "John and Mattis": "JOHNMATS",
    "John and Mitchell Ct.": "JOHNMCHLCT",
    "John and McKinley": "JOHNMCNLY",
    "John and New": "JOHNNEW",
    "John and Pine": "JOHNPINE",
    "John and Prairie": "JOHNPRRE",
    "John and Prospect": "JOHNPSPCT",
    "John and Ridgeway": "JOHNRGWAY",
    "John and Russell": "JOHNRSL",
    "John and Victor": "JOHNVCTR",
    "John and Willis": "JOHNWILS",
    "John and Westlawn": "JOHNWLWN",
    "John and Western": "JOHNWSTRN",
    "Japan House": "JPN",
    "Kirby and Alma": "KBYALMA",
    "Kirby and Arrow": "KBYARW",
    "Kirby and Bellepark": "KBYBLPK",
    "Kirby and Carolyn": "KBYCAROL",
    "Kirby and Cobblefield": "KBYCBLFLD",
    "Kirby and Cambridge": "KBYCMBG",
    "Kirby and Carriage Way": "KBYCRGWY",
    "Kirby and Coronado": "KBYCRNDO",
    "Kirby and Crescent": "KBYCRSNT",
    "Kirby and Duncan": "KBYDNCN",
    "Kirby and Dodds": "KBYDODD",
    "Kirby and Dawson": "KBYDWSN",
    "Kirby and Grandview": "KBYGDVWW",
    "Kirby and Grandview West": "KBYGDVWW",
    "Kirby and Greencroft": "KBYGRNCFT",
    "Kirby and Kenwood": "KBYKNWD",
    "Kirby and Lincoln Rd.": "KBYLCLNRD",
    "Kirby and Mattis": "KBYMATS",
    "Kirby and Mayfair": "KBYMYFR",
    "Kirby and Neil": "KBYNEIL",
    "Kirby and Oak": "KBYOAK",
    "Kirby and Park Haven": "KBYPRKHVN",
    "Kirby and Ridge": "KBYRDGRD",
    "Kirby and Rose": "KBYROSE",
    "Kirby and Rose": "KBYRSWD",
    "Kirby and Rosewood": "KBYRSWD",
    "Kirby and Scottsdale": "KBYSCTDL",
    "Kirby and Stratford": "KBYSRTFRD",
    "Kirby and State": "KBYSTE",
    "Kirby and Valley Rd.": "KBYVYRD",
    "Kirby and Waverly": "KBYWAVE",
    "Kirby and Westfield": "KBYWSFLD",
    "Kirby and Western": "KBYWSTRN",
    "Kerr and Berkley": "KERBRKLY",
    "Kerr and Cunningham": "KERCNHM",
    "Kerr and Carroll": "KERCROL",
    "Kerr and Division": "KERDVSION",
    "Kerr and Geraldine": "KERGRLDNE",
    "Kerr and Highlands": "KERHGHLNDS",
    "Kerr and Ward": "KERWRD",
    "Kinch and Easy": "KNCHEASY",
    "Kinch and Lantern Hill": "KNCHLH",
    "Kinch and Rainbow View": "KNCHRAIN",
    "Kenyon and Cracker Barrel": "KNYNCRKRB",
    "Kenyon at Eastland Suites": "KNYNESTLND",
    "Kenyon at Steak and Shake": "KNYNSTKSHK",
    "Kettering and Linview": "KPDLNVW",
    "Krannert Center": "KRANNERT",
    "Kirby and Glenshire": "KRBYGLNSHR",
    "Kirby and Mullikin": "KRBYMLKN",
    "LAR": "LAR",
    "Liberty and Betsy Ross": "LBRTYBTSYRS",
    "Liberty and Columbia": "LBRTYCLMBA",
    "Liberty and Jefferson": "LBRTYJEF",
    "St. Mathews": "LCNSR",
    "Lincolnshire and Foothill": "LCNSRFTHL",
    "Leggett and Bardeen": "LGGTBRDN",
    "Logan and 1st": "LGN1ST",
    "Lakeview and Wedgewood": "LKVWWGWD",
    "Lakeview and Worthington": "LKVWWTGTN",
    "Lincoln and Anthony": "LNCLNANT",
    "Lincoln and Bradley": "LNCLNBRAD",
    "Lincoln and College Ct.": "LNCLNCC",
    "Lincoln and Church": "LNCLNCHCH",
    "Lincoln and Delaware": "LNCLNDE",
    "Lincoln and Eads": "LNCLNEADS",
    "Lincoln and Florida": "LNCLNFL",
    "Lincoln and Hill": "LNCLNHIL",
    "Lincoln and Illinois": "LNCLNIL",
    "Lincoln and Kettering Park": "LNCLNKING",
    "Lincoln and Killarney": "LNCLNKLRNY",
    "Lincoln and Oregon": "LNCLNOR",
    "Lincoln and Pennsylvania": "LNCLNPA",
    "Lincoln and Park": "LNCLNPK",
    "Lincoln and St. Mary's": "LNCLNSMR",
    "Lincoln and St. Marys": "LNCLNSMR",
    "Lincoln and Sunset": "LNCLNSNST",
    "Lincoln and Vermont": "LNCLNVT",
    "Lincoln and Wascher": "LNCLNWSCR",
    "Lyndhurst and Lyndhurst Village Ct.": "LNHSTARBR",
    "Lyndhurst and Arbour": "LNHSTARBR1",
    "Lyndhurst and Bedford": "LNHSTBDFD",
    "Lyndhurst and Burwash": "LNHSTBRWS",
    "Lyndhurst and Evergreen Circle": "LNHSTEGRN",
    "Lyndhurst and Lyndhurst Village Ct.": "LNHSTLNVCT",
    "Lyndhurst and Magnolia": "LNHSTMAGN",
    "Lyndhurst and Old Maple Lane": "LNHSTOML",
    "Lyndhurst and Park Ln": "LNHSTPKLN",
    "Linview and Killarney": "LNVWKLRNY",
    "Lierman and Bartell": "LRMNBRTL",
    "Lierman and Hunter": "LRMNHNTR",
    "Lakeshore and Maynard": "LSDMYNRD",
    "Lincoln Square Courthouse": "LSE",
    "Lincoln Square Garage East": "LSE",
    "Lincoln Square Garage South": "LSE",
    "Lawndale and Bellepark": "LWNDLBLPK",
    "Lawndale and Centennial": "LWNDLCENT",
    "Lynn and Park": "LYNPRK",
    "Mattis and Alton": "MATSALTN",
    "Mattis and Anita": "MATSANTA",
    "Mattis and Broadmoor": "MATSBDMR",
    "Mattis and Bloomington": "MATSBLOM",
    "Mattis and Branch": "MATSBRCH",
    "Mattis and Chevy Chase": "MATSCHEVY",
    "Mattis and Cypress": "MATSCYPS",
    "Mattis and Devonshire": "MATSDVN",
    "Mattis and Glenn Park": "MATSGLNPK",
    "Mattis and Gentry Square South": "MATSGNSQ",
    "Mattis and Henry": "MATSHNRY",
    "Mattis and Harbor Point": "MATSHRBR",
    "Mattis and Interstate": "MATSINT",
    "Mattis and Ivy Ct. North": "MATSIVYN",
    "Mattis and Ivy Ct. South": "MATSIVYS",
    "Mattis and Meadow": "MATSMDWDR",
    "Mattis North Apartments": "MATSMNA",
    "Mattis and Princeton": "MATSPRNCTN",
    "Mattis and Round Barn": "MATSRBR",
    "Mattis and Sangamon": "MATSSANG",
    "Mattis and Sheridan": "MATSSHRDN",
    "Mattis and Sumac": "MATSSMC",
    "Mattis and Southwood": "MATSSTHWD",
    "Mattis and Stonegate": "MATSSTNGT",
    "Mattis at Post Office": "MATSUSPS",
    "Mattis and Windsor": "MATSWDSR",
    "Mattis and William": "MATSWLM",
    "McKinley and Beardsley": "MCNLYBRD",
    "McKinley and Eureka": "MCNLYERKA",
    "McKinley and Harvard": "MCNLYHVAD",
    "McKinley and Maple": "MCNLYMPL",
    "McKinley and Tremont": "MCNLYTRMNT",
    "MacArthur and California": "MCRTRCA",
    "MacArthur and MacArthur Ct.": "MCRTRCT",
    "MacArthur and High": "MCRTRHI",
    "MacArthur and Illinois": "MCRTRIL",
    "Meijer Dr. at Meijer": "MEIJER",
    "Mercury and Apollo": "MERCAPLO",
    "Mercury at FedEx": "MERCFEDEX",
    "Mercury and Gemini": "MERCGEMCT",
    "McHenry and Anderson": "MHRYADRSN",
    "McHenry and Combes": "MHRYCMBS",
    "McHenry and Cottage Grove": "MHRYCTGRV",
    "McHenry and Fletcher": "MHRYFLCHR",
    "McHenry and Lynn": "MHRYLYN",
    "McHenry and Lynn St. 1": "MHRYLYN1",
    "McHenry and Lynn St. #2": "MHRYLYN2",
    "McHenry and Lynn - East": "MHRYLYNE",
    "McHenry and Philo": "MHRYPHILO",
    "McHenry and Pond": "MHRYPND",
    "McHenry and Vawter": "MHRYVWTR",
    "Michigan and Green Ridge": "MIGRNRDG",
    "Michigan and Kinch": "MIKNCH",
    "Michigan and Smith": "MISMITH",
    "Meijer Drive and Prospect": "MJRPSPCT",
    "Market Place and Wilbur": "MKPLCWLB",
    "Market and Bellefontaine": "MKTBELL",
    "Barnes and Noble Books": "MKTBNB",
    "Market and Bradley": "MKTBRAD",
    "Market and Garwood": "MKTGAR",
    "Market and Kenyon": "MKTKNYN",
    "Market and Logan": "MKTLGN",
    "Market and Mercury": "MKTMERC",
    "Market and Marketview": "MKTMKTV",
    "Market and Paul": "MKTPAUL",
    "Market and Peach Tree": "MKTPCH",
    "Market Place": "MKTPLC",
    "Market Place and Convenience Dr.": "MKTPLCCD",
    "Market Place North Entrance": "MKTPLCN",
    "Mkt Plc North Ent. and Market": "MKTPLCNMKT",
    "Market Place South": "MKTPLCS",
    "Market Place Southeast": "MKTPLCSE",
    "Market Place West": "MKTPLCW",
    "Market and Roper": "MKTRPR",
    "Market and Tulip Tree": "MKTTLP",
    "Marketview at Marketview Center": "MKTV",
    "Marketview and Anthony": "MKTVANT",
    "Marketview at Sams": "MKTVSAMS",
    "Market and Wallace": "MKTWLACE",
    "Market and Wilbur": "MKTWLBR",
    "Mullikin and Copper Ridge": "MLKNCPRRG",
    "Mullikin and Crossgate": "MLKNCRSGT",
    "Mullikin and Curtis Meadow": "MLKNCTSMDW",
    "Mullikin and Doverbrook": "MLKNDVRBRK",
    "Mullikin and Graves Ct.": "MLKNGRVCT",
    "Mullikin and Ironwood": "MLKNIRNWD",
    "Mullikin and Remington Way": "MLKNRMGNTN",
    "Mullikin and Stonebridge": "MLKNSTNBDG",
    "Mullikin and Trostshire": "MLKNTRSTSHR",
    "Mullikin and Villa": "MLKNVLA",
    "Mullikin and Westborough": "MLKNWSTBRGH",
    "Main and University": "MN150",
    "Main and Art Bartell": "MNABD",
    "Main and Broadway": "MNBRDWY",
    "Main and Brady": "MNBRDY",
    "Main and Chestnut": "MNCHSNT",
    "Main and Cottage Grove": "MNCTGRV",
    "Main and Dodson": "MNDDSN",
    "Main and Dewey": "MNDWY",
    "Main and Ennis": "MNENIS",
    "Main and Fremont": "MNFREMNT",
    "Main and Glover": "MNGLVR",
    "Main and Grossbach": "MNGRSBCH",
    "Main and Grove": "MNGRV",
    "Main and Hartle": "MNHTL",
    "Main at ILEAS": "MNILEAS",
    "Main and Lierman": "MNLRMN",
    "Main and Lynn": "MNLYN",
    "Main and Maple": "MNMPL",
    "Main and Poplar": "MNPLR",
    "Main and Scottswood": "MNSCWD",
    "Main and Smith": "MNSMITH",
    "Main and Urbana": "MNUBNA",
    "Main and Vine": "MNVIN",
    "Main and Webber": "MNWBR",
    "Main and Walnut": "MNWLNT",
    "Maplepark and Lawndale": "MPLPKLWNDL",
    "Maplepark and Maplewood": "MPLPKMPLWD",
    "Maplepark and Sangamon": "MPLPKSANG",
    "Maplepark and William": "MPLPKWLM",
    "Moraine and Lake Shore": "MRANLSD",
    "Mattis and Green": "MTSGRN",
    "Mattis and Healey": "MTSHLY",
    "Mayfair and Broadmoor": "MYFRBDMR",
    "Mayfair and Georgetown": "MYFRGTOWN",
    "Mayfair and Lincolnshire": "MYFRLCLNSH",
    "Mayfair and Old Farm": "MYFROF",
    "Mayfair and Sandpiper": "MYFRSNFR",
    "Mayfair and Theodore": "MYFRTDR",
    "Mayfair and Weathervane": "MYFRWTRVN",
    "Maynard and Coventry": "MYNDCVTRY",
    "Myra Ridge and Autumn Ridge": "MYRAAUTM",
    "Myra Ridge and Ridge Park": "MYRARGPK",
    "Myra Ridge and Silver Hill": "MYRASLVHL",
    "Myra Ridge and Trails": "MYRATRLS",
    "Neil and Anthony": "NEILANT",
    "Neil and Arcadia": "NEILARC",
    "Neil and Bellefontaine": "NEILBELL",
    "Neil and Beardsley": "NEILBRD",
    "Neil and Burwash": "NEILBRWS",
    "Neil and Center Dr.": "NEILCD",
    "Neil and Columbia": "NEILCLMBA",
    "Neil and Center": "NEILCNTR",
    "Neil and Edgebrook": "NEILEGB",
    "Neil and Eureka": "NEILERKA",
    "Neil and Garwood": "NEILGAR",
    "Neil and Hill": "NEILHIL",
    "Neil and Healey": "NEILHLY",
    "Neil and Hessel": "NEILHSL",
    "Neil and Interstate": "NEILINTR",
    "Neil and Kenyon": "NEILKNYN",
    "Neil and Marketview": "NEILMKTV",
    "Neil and Marshall": "NEILMSHL",
    "Neil and North": "NEILN",
    "Neil and Springfield": "NEILSPFLD",
    "Neil and Stadium": "NEILSTDM",
    "Neil and Town Center Apt.": "NEILTCA",
    "Neil and Twins": "NEILTWN",
    "Neil and Vine": "NEILVIN",
    "Neil and Washington": "NEILWASH",
    "Neil and White": "NEILWHT",
    "Neil and Walingford": "NEILWLGFRD",
    "Napleton and Anthony": "NPLTNANTHNY",
    "Northwood and George": "NRTHWDGRG",
    "Nevada and Gregory Pl.": "NVGRGPL",
    "Nevada and Lincoln": "NVLNCLN",
    "Newport and Landis Farm": "NWPRTLNDSFRM",
    "Newport and Milford": "NWPRTMLFRD",
    "Newton and Leggett": "NWTNLGGT",
    "Newton and Nobel": "NWTNNBL",
    "Newton and Newmark": "NWTNNWMK",
    "Newton and Research": "NWTNRSRCH",
    "Oak St.": "OAK",
    "Oak and Anthony": "OAKANT",
    "Oak and Gerty": "OAKGTY",
    "Oak and Kenyon": "OAKKNYN",
    "Orchard Downs Mid-North": "ODMIDN",
    "Orchard Downs Mid-South": "ODMIDS",
    "Orchard Downs North Shelter": "ODNS",
    "Orchard Downs South Shelter": "ODSS",
    "One Illinois North": "ONENORTH",
    "One Illinois South": "ONESOUTH",
    "Pennsylvania and 4th": "PA4TH",
    "Pennsylvania and 6th": "PA6TH",
    "Penn and Anderson": "PAADRSN",
    "Ag. Engineering": "PAAG",
    "Penn and Broadway": "PABDWY",
    "Penn and Busey": "PABUSEY",
    "Penn and Carle": "PACARL",
    "Pennsylvania Ct.": "PACT",
    "Penn and Dorner": "PADNR",
    "Penn and Goodwin": "PAGWN",
    "Penn and Kinch": "PAKNCH",
    "Pennsylvania at Law Building": "PALAW",
    "Penn and Maryland": "PAMD",
    "Penn and Orchard": "PAORCH",
    "Pennsylvania at PAR": "PAPAR",
    "PAR": "PAR",
    "Pennsylvania and Race": "PARACE",
    "Parkview": "PARKVIEW",
    "Penn and Vine": "PAVIN",
    "Penn and Wiley": "PAWILEY",
    "Pebblebrook and Bluegrass": "PBLBRKBLGRS",
    "Pebblebrook and Rockdale": "PBLBRKRKDL",
    "Winfield Village Lot B": "PDKELOTB",
    "Winfield Village Lot G": "PDKWLOTG",
    "Winfield Village Lot M": "PDKWLOTM",
    "Krannert Art Museum": "PDYKAM",
    "Philo and Briarcliff": "PHILOBCLF",
    "Philo and Colorado": "PHILOCO",
    "Philo and Fairlawn": "PHILOFRLN",
    "Philo and Harding": "PHILOHRDG",
    "Philo and Laurel": "PHILOLRL",
    "Philo and Mumford": "PHILOMFRD",
    "Philo and Michigan": "PHILOMI",
    "Philo and Pennsylvania": "PHILOPA",
    "Philo and Scovill": "PHILOSCVL",
    "Philo and Silver": "PHILOSLVR",
    "Philo and Windsor": "PHILOWDSR",
    "Park and Central": "PKCNTRL",
    "Parkland College": "PKLN",
    "Park Lane and Bedford": "PKLNBDFD",
    "Parkland Ct. and Bradley": "PKLNCTBRAD",
    "Park Lane and Stanford": "PKLNSTFD",
    "Park and Mathews": "PKMAT",
    "Park and McCullough": "PKMCCLGH",
    "Perkins and Cherokee": "PKNSCHKE",
    "Perkins and Cooks Ln.": "PKNSCOOK",
    "Perkins and Carroll": "PKNSCROL",
    "Perkins and Eastern": "PKNSEAST",
    "Perkins and Highcross": "PKNSHICRS",
    "Perkins and Ivanhoe": "PKNSIVAN",
    "Perkins and Richard": "PKNSRICH",
    "Perkins and Raintree": "PKNSRNTRW",
    "Park and Romine": "PKRMN",
    "Park and Wright": "PKWRT",
    "Paula and Cynthia": "PLACYNTHA",
    "Paula and Garden Hills": "PLAGH",
    "Paula and Honeysuckle": "PLAHNYSKL",
    "Paula and Jeanne": "PLAJEANNE",
    "Paula and Joanne": "PLAJOANE",
    "Paula and Kirk Ln.": "PLAKIRK",
    "Paula and Larkspur": "PLALRKSPR",
    "Paula and Mattis": "PLAMATS",
    "Paula and McKinley": "PLAMCNLY",
    "Paula and Melanie": "PLAMELNE",
    "Paula and Powers": "PLAPWRS",
    "Plastipak": "PLASTIPAK",
    "Transit Plaza": "PLAZA",
    "Pomona and Bradley": "PMNABRAD",
    "Pomona and Deske Ct.": "PMNADSK",
    "Pomona and Ed Hoffman": "PMNAEH",
    "Pomona and Heritage": "PMNAHRTG",
    "Pomona and Santa Ana": "PMNASTANA",
    "Pinecrest and Porterfield": "PNCRSTPRTFLD",
    "Pinecrest and Staley": "PNCRSTSTLY",
    "Peppermill and Pebblebrook": "PPRMLPBLBRK",
    "Plant Sciences Lab": "PSL",
    "Prospect and Ayrshire Cir.": "PSPCTASRC",
    "Prospect and Ayrshire": "PSPCTASRD",
    "Prospect and Broadmoor": "PSPCTBDMR",
    "Prospect and Beardsley": "PSPCTBRD",
    "Prospect and Columbia": "PSPCTCLMBA",
    "Prospect and Dennison": "PSPCTDNSN",
    "Prospect and Devonshire": "PSPCTDVN",
    "Prospect and Eureka": "PSPCTERKA",
    "Prospect and Floral Park": "PSPCTFLRPK",
    "Prospect and Francis": "PSPCTFRAN",
    "Prospect and Francis": "PSPCTFRNS",
    "Prospect and Galen": "PSPCTGALN",
    "Prospect and Green": "PSPCTGRN",
    "Prospect and Healey": "PSPCTHEALY",
    "Prospect and Hill": "PSPCTHILL",
    "Prospect and Harvard": "PSPCTHVD",
    "Prospect and Interstate": "PSPCTINTER",
    "Prospect and John": "PSPCTJOHN",
    "Prospect and Kirby": "PSPCTKBY",
    "Prospect and Kent": "PSPCTKENT",
    "Prospect and Lincolnshire": "PSPCTLNSH",
    "Prospect at Meijer": "PSPCTMJR",
    "Prospect and Marketview": "PSPCTMKTV",
    "Prospect and Maple": "PSPCTMPL",
    "Prospect and Park Ln.": "PSPCTPKLN",
    "Prospect and Pioneer": "PSPCTPNR",
    "Prospect and Sherwood Tr.": "PSPCTSHWD",
    "Prospect and Tremont": "PSPCTTRMNT",
    "Prospect and Vine": "PSPCTVIN",
    "Prospect and Ventura": "PSPCTVTRA",
    "Prospect and Washington": "PSPCTWASH",
    "Queensway": "QNWAY1",
    "Queensway and Roland": "QNWAYRLND",
    "Race and California": "RACECA",
    "Race and Delaware": "RACEDE",
    "Race and High St.": "RACEHIGH",
    "Race and Holmes": "RACEHLMS",
    "Race and Iowa": "RACEIA",
    "Race and Illinois": "RACEIL",
    "Race and Indiana": "RACEIN",
    "Meadowbrook Park": "RACEMBRK",
    "Race and Meadow": "RACEMDW",
    "Race and McHenry": "RACEMHRY",
    "Race and Michigan": "RACEMI",
    "Race and Main": "RACEMN",
    "Race and Montclair": "RACEMTCLR",
    "Race and Mumford": "RACEMUMFRD",
    "Race and Nevada": "RACENV",
    "Race and Oregon": "RACEOR",
    "Race and Sherwin": "RACESWND",
    "Race at Stone Creek Church": "RACEUA",
    "Race and Vermont": "RACEVT",
    "Race and Washington #1": "RACEWASH1",
    "Race and Washington #2": "RACEWASH2",
    "Race and Windsor": "RACEWDSR",
    "Race and Whitehall Ct.": "RACEWTHL",
    "Round Barn and Country Fair Dr.": "RBRCFD",
    "Highcross and Kyle": "RE",
    "Restoration Urban Ministries": "RESTURBMIN",
    "Rolling Acres and Marjorie": "RLACRMRJ",
    "Roland and Aztec": "RLNDAZTEC",
    "Roland and Comanche": "RLNDCMCHE",
    "Roland and Dobbins": "RLNDDBNS",
    "Roland and Walters": "RLNDWTRS",
    "Romine and Bradley": "RMNBRAD",
    "Romine and Beardsley": "RMNBRD",
    "Romine and Eads": "RMNEADS",
    "Romine and Ellis": "RMNELLIS",
    "Romine and Eureka": "RMNERKA",
    "Romine and Tremont": "RMNTRMNT",
    "Randolph and Avondale": "RNDLFAVNDL",
    "Randolph and Bradley": "RNDLFBRAD",
    "Randolph and Beardsley": "RNDLFBRD",
    "Randolph and Charles": "RNDLFCHAS",
    "Randolph and Clark": "RNDLFCLARK",
    "Randolph and Columbia": "RNDLFCLMBA",
    "Randolph and Ells": "RNDLFELS",
    "Randolph and Eureka": "RNDLFERKA",
    "Randolph and Hill": "RNDLFHIL",
    "Randolph and Healey": "RNDLFHLY",
    "Randolph and John": "RNDLFJOHN",
    "Randolph and Maple": "RNDLFMPL",
    "Randolph and Springfield": "RNDLFSPFLD",
    "Randolph and Stanage": "RNDLFSTNAG",
    "Randolph and Tremont": "RNDLFTRMNT",
    "Randolph and University": "RNDLFUNI",
    "Randolph and Vine": "RNDLFVIN",
    "Randolph and Washington": "RNDLFWASH",
    "Randolph and White": "RNDLFWHT",
    "Randolph and William": "RNDLFWLM",
    "Research at Hobbico": "RSRCHHBCO",
    "Scottswood and Calif. Ct.": "SCWDCACT",
    "Scottswood and Illinois": "SCWDIL",
    "Scottswood and Nevada": "SCWDNV",
    "Scottswood and Oregon": "SCWDOR",
    "Springer and Country Fair Dr.": "SGRCFD",
    "Skyline and Newport": "SKYLNNWPRT",
    "Silver and Cottage Grove": "SLVRCTGRV",
    "Silver and Fletcher": "SLVRFLCHR",
    "Silver and Vawter": "SLVRVWTR",
    "Slayback and Carrie": "SLYBKCRE",
    "Slayback and Dodson West": "SLYBKDOD",
    "Slayback and Ira": "SLYBKIRA",
    "Slayback and McGee": "SLYBKMG",
    "Slayback and Smith": "SLYBKSMITH",
    "Smith and U.S. 150": "SMITH150",
    "Smith and Carrie": "SMITHCRE",
    "St. Mary's and Griffith": "SMRGRIF",
    "Smith and Rainbowview": "SMRNBVW",
    "St. Mary's and Neil": "SMRNEIL",
    "St. Mary's and Oak": "SMROAK",
    "Summersage and Switchgrass": "SMRSGSWTCHGRS",
    "Springfield at Country Fair": "SPFLD",
    "Springfield and Birch": "SPFLDBRCH",
    "Springfield and Busey": "SPFLDBSY",
    "Springfield and Country Fair Dr.": "SPFLDCFD",
    "Springfield and Chicago": "SPFLDCHI",
    "Springfield and Duncan": "SPFLDDNCN",
    "Springfield and Draper": "SPFLDDRPR",
    "Springfield and Edwin": "SPFLDEDWN",
    "Springfield and Elm": "SPFLDELM",
    "Springfield and Fair": "SPFLDFAIR",
    "Springfield and Fieldstone": "SPFLDFLDSTN",
    "Springfield and Garfield": "SPFLDGRFLD",
    "Springfield and Gregory St.": "SPFLDGRGST",
    "Springfield and Highland": "SPFLDHILND",
    "Springfield and Harvey": "SPFLDHVY",
    "Springfield and James": "SPFLDJAS",
    "Springfield and Kenwood": "SPFLDKNWD",
    "Springfield and Lynn": "SPFLDLYN",
    "Springfield and Mattis": "SPFLDMATS",
    "Springfield and McKinley": "SPFLDMCNLY",
    "Springfield and New": "SPFLDNEW",
    "Springfield and Pine": "SPFLDPINE",
    "Springfield at Phillips Rec. Ctr": "SPFLDPRC",
    "Springfield and Prairie": "SPFLDPRRE",
    "Springfield and Prospect": "SPFLDPSPCT",
    "Springfield and Ridgeway": "SPFLDRGWY",
    "Springfield and Russell": "SPFLDRSL",
    "Springfield and Royal Ct.": "SPFLDRYLCT",
    "Springfield and Staley": "SPFLDSTLY",
    "Springfield and VanDoren": "SPFLDVNDRN",
    "Springfield and Willis": "SPFLDWLS",
    "Springfield and Westlawn": "SPFLDWLWN",
    "Springhill and Glenhill": "SPGHLGLNHL",
    "Susan Stone and Galena": "SSTNGLNA",
    "Susan Stone and Jane Ann Ct.": "SSTNJACT",
    "Susan Stone and Jane Lee Ct.": "SSTNJACT",
    "Susan Stone and Moss": "SSTNMOS",
    "Susan Stone and Myra Ridge": "SSTNMYRA",
    "Susan Stone and Plains Ct.": "SSTNPLN",
    "Susan Stone and Summit": "SSTNSMT",
    "Sussex and Oakmont": "SSXOKMNT",
    "Sussex and Southfield": "SSXSFLD",
    "Sussex and Windward": "SSXWIND",
    "Sussex and Waterford": "SSXWTRFD",
    "Stadium and Oak": "STDMOAK",
    "State and Avondale": "STEAVNDL",
    "State and Birch": "STEBRCH",
    "State and Beardsley": "STEBRD",
    "State and Buena Vista": "STEBV",
    "State and Cedar": "STECDR",
    "State and Charles": "STECHAS",
    "State and Clark": "STECLARK",
    "State and Columbia": "STECLMBA",
    "State and Ells": "STEELS",
    "State and Eureka": "STEERKA",
    "State and Hill": "STEHIL",
    "State and Healey": "STEHLY",
    "State and Hessel": "STEHSL",
    "State and John": "STEJOHN",
    "State and Maple": "STEMPL",
    "State and Park": "STEPK",
    "State and Springfield": "STESPFLD",
    "State and Stanage": "STESTNAG",
    "State and Trade Center Dr.": "STETC",
    "State and Tremont": "STETRMNT",
    "State and University": "STEUNI",
    "State and Vine": "STEVIN",
    "State and Washington": "STEWASH",
    "State and White": "STEWHT",
    "State and William": "STEWLM",
    "Staley and Amherst": "STLYAMHT",
    "Staley and Clubhouse": "STLYCLBHS",
    "Staley and Colleen": "STLYCLEEN",
    "Staley and Copper Ridge": "STLYCPRRDG",
    "Staley and Inverness": "STLYINV",
    "Staley and Kirby": "STLYKBY",
    "Staley and Kearns": "STLYKRNS",
    "Staley and Turnberry": "STLYTRNBRY",
    "St. Mathews": "STMAT",
    "Stone Creek and Bohn": "STNCRKBN",
    "Stone Creek and Stillwater Landing": "STNCRKSTLWTR",
    "Stone Creek and Venturi": "STNCRKVNTRI",
    "Colorado at Steer Place": "STP",
    "Sunnycrest": "SUNNYCREST",
    "Savoy Walmart": "SWALMART",
    "Sherwin and Pond Ridge": "SWNDPNDR",
    "Sherwin and Persimmon": "SWNDPSMN",
    "Sherwin and Sherwin Cir.": "SWNDSWNC",
    "Sherwin and Sherwin Cir 2": "SWNDSWNC2",
    "Sherwin and Yankee Ridge": "SWNDYNKR",
    "Switchgrass and Trailway": "SWTCHGRSTRLWY",
    "Switchgrass and Wildflower": "SWTCHGRSWLDFLWR",
    "Tatman Ct. and Highcross": "TAT130",
    "Town and Country Apts.": "TCA",
    "Town Center at Meijer": "TCBMJR",
    "Town Center and Menards": "TCBMNRDS",
    "Town Center and Moreland": "TCBMRLND",
    "Town Center and Neil": "TCBNEIL",
    "Town Center and Prospect": "TCBPSPCT",
    "Town Center at Target": "TCBTGT",
    "Toalson and Interstate": "TLSNINTER",
    "Timbergate and Cherry Hills": "TMGTCHHL",
    "Thompson Park": "TMPSNPK",
    "Trails and Baronry": "TRLSBRN",
    "Trails and Chatham": "TRLSCHAT",
    "Trails and Fawn Hill": "TRLSFWN",
    "Trails and Philo": "TRLSPHILO",
    "Urbana High School": "UHS",
    "U of I Credit Union": "UICU",
    "Urbana Middle School": "UMS",
    "University and 2nd": "UNI2ND",
    "University and 4th": "UNI4TH",
    "University and 6th": "UNI6TH",
    "University and Ash": "UNIASH",
    "University and Central": "UNICENT",
    "University and Cottage Grove": "UNICTGRV",
    "University and Draper": "UNIDRPR",
    "University and Elm": "UNIELM",
    "University and Fair": "UNIFAIR",
    "University and Goodwin": "UNIGWN",
    "University and Hickory": "UNIHKRY",
    "University and Harvey": "UNIHVY",
    "University and James": "UNIJAS",
    "University and Lake": "UNILAKE",
    "University and Lierman": "UNILRMN",
    "University and Lynn": "UNILYN",
    "University and Mattis": "UNIMATS",
    "University and McCullough": "UNIMCLGH",
    "University and McKinley": "UNIMCNLY",
    "University and Maple": "UNIMPL",
    "University and Neil": "UNINEIL",
    "University and New": "UNINEW",
    "University and Prairie": "UNIPRRE",
    "University and Prospect": "UNIPSPCT",
    "University and Race": "UNIRACE",
    "University and Randolph": "UNIRNDLF",
    "University and Russell": "UNIRSL",
    "University and Sabin": "UNISBN",
    "University and Sycamore": "UNISCMR",
    "": "UNITD4140	University at MTD",
    "University and Victor": "UNIVCTR",
    "University and Vine": "UNIVIN",
    "University and Willis": "UNIWLS",
    "University and Wright": "UNIWRT",
    "Urbana Meijer": "URBMEIJ",
    "Urbana Walmart": "UWALMART",
    "Vet-Med": "VETMED",
    "Vine and Burkwood Ct.": "VINBKWD",
    "Vine and Brookens": "VINBRKNS",
    "Vine and California": "VINCA",
    "Vine and Colorado": "VINCO",
    "Vine and Evergreen Ct.": "VINEGRN",
    "Vine and Elm": "VINELM",
    "Vine and Michigan": "VINEMI",
    "Vine and Fairlawn": "VINFRLN",
    "Vine and George Huff": "VINGHF",
    "Vine and Green": "VINGRN",
    "Vine and Holmes": "VINHLMS",
    "Vine and Harris": "VINHRIS",
    "Vine and Illinois": "VINIL",
    "Vine and Lynn": "VINLYN",
    "Vine and McKinley": "VINMCNLY",
    "Vine and Mumford": "VINMFRD",
    "Vine and McHenry": "VINMHRY",
    "Vine and Montclair": "VINMNTCLR",
    "Vine and Nevada": "VINNV",
    "Vine and Oregon": "VINOR",
    "Vine and Pell Cir.": "VINPELL",
    "Vine and Prairie": "VINPRRE",
    "Vine and Scovill": "VINSCVL",
    "Vine and Sunnycrest": "VINSNYC",
    "Vine and Shurts": "VINSRTS",
    "Vine and Washington": "VINWASH",
    "Vine and Willis": "VINWLS",
    "Vine and Water": "VINWTR",
    "Viking North": "VKINGN",
    "Viking South": "VKINGS",
    "Valerie and Alpine": "VLRALPN",
    "Valerie and Meaghan": "VLRMGHN",
    "Vance and Napleton": "VNCENPLTN",
    "Vermont and Kinch": "VTKNCH",
    "Champaign Walmart": "WALMART",
    "Washington and 2nd": "WASH2ND",
    "Washington and 3rd": "WASH3RD",
    "Washington and 4th": "WASH4TH",
    "Washington and Ash": "WASHASH",
    "Washington and Broadway": "WASHBDWY",
    "Washington and Country Squire": "WASHCSQR",
    "Washington and Hickory": "WASHHKRY",
    "Washington and Kinch": "WASHKNCH",
    "Washington and Lanore": "WASHLNR",
    "Washington and Lierman": "WASHLRMN",
    "Washington and MacArthur": "WASHMCRTR",
    "Washington and Phillips": "WASHPHLPS",
    "Washington and Rainbow View": "WASHRAIN",
    "Washington School": "WASHSCL",
    "Washington and Scottswood": "WASHSCWD",
    "Washington and Smith": "WASHSMITH",
    "Washington and Timothy Tr.": "WASHTIM",
    "Woodfield and Arbor Town": "WDFLDABT",
    "Woodfield and Curtis": "WDFLDCTS",
    "Wedgewood and Timbergate": "WDGWDTMGT",
    "Windsor Rd.": "WDSR",
    "Windsor and Bel Air": "WDSRBA",
    "Windsor and Brookshire": "WDSRBKSR",
    "Windsor and Boulder": "WDSRBLDR",
    "Christie Clinic": "WDSRCCS",
    "Windsor and Cherry Hills": "WDSRCHHL",
    "Windsor and Carlisle": "WDSRCLSL",
    "Clark Lindsey Village": "WDSRCLV",
    "Windsor and Crossing Ct.": "WDSRCRSNG",
    "Windsor and Donnybrook": "WDSRDNBK",
    "Windsor and Duncan": "WDSRDNCN",
    "Windsor and Phinney": "WDSRFNY",
    "Windsor and Imperial": "WDSRIMP",
    "Windsor and Jordan": "WDSRJDN",
    "Windsor and Lakewood": "WDSRLKWD",
    "Windsor and Lynn": "WDSRLYN",
    "Windsor and Melrose": "WDSRMLRS",
    "Windsor and Monterey": "WDSRMTRY",
    "Windsor and Morrissey Park": "WDSRMYPK",
    "Windsor and Myra Ridge": "WDSRMYRA",
    "Windsor and Prospect": "WDSRPSPCT",
    "Windsor and Scottsdale": "WDSRSCTDL",
    "Windsor and Susan Stone": "WDSRSSTN",
    "Windsor and Stillwater": "WDSRSTLW",
    "Windsor and Vine": "WDSRVIN",
    "Windsor and Village Green": "WDSRVLGGRN",
    "Windsor and Valleybrook": "WDSRVYBK",
    "Windsor West Apts": "WDSRWEST",
    "Windsor and Windward": "WDSRWIND",
    "Windsor and Winchester": "WDSRWNCH",
    "Windsor and Willowbrook": "WDSRWWBK",
    "Westgate Apts.": "WESTGATE",
    "White and 1st": "WHT1ST",
    "White and 2nd": "WHT2ND",
    "White and 4th": "WHT4TH",
    "White and 6th": "WHT6TH",
    "White and Wright": "WHTWRT",
    "Willow and Baker": "WILLOWBKR",
    "Willow and Kenyon": "WILLOWKNYN",
    "Windward and Autumnwood": "WINDATMWD",
    "Windward and Countryside": "WINDCNTYSD",
    "Windward Point": "WINDPT",
    "Windward and Waterford": "WINDWTRFD",
    "Wildflower and Chickory": "WLDFLRCKRY",
    "Wildflower and Trailway": "WLDFLRTRLWY",
    "Willow and Beason": "WLLWBESN",
    "William and Bellepark": "WLMBLPRK",
    "William and Centennial": "WLMCENT",
    "William and Dogwood": "WLMDGWD",
    "William and Duncan": "WLMDNCN",
    "William and Goldenview": "WLMGLDVW",
    "William and Kenwood": "WLMKNWD",
    "William and Maplepark": "WLMMPLPK",
    "William and Oakcrest": "WLMOKCRST",
    "William and Stratford": "WLMSTFRD",
    "Walnut and Columbia": "WLNTCLMBA",
    "Walnut and Logan": "WLNTLGN",
    "Walnut and University": "WLNTUNI",
    "Walnut and Washington": "WLNTWASH",
    "Bradley at WLRW": "WLRW",
    "Williamsburg": "WMBG",
    "Williamsburg and Garden Hills": "WMBGGH",
    "Williamsburg and Mattis": "WMBGMATS",
    "Williamsburg and Summerlin": "WMBGSMLN",
    "Williamsburg and Summit Ridge": "WMBGSTRG",
    "Williamsburg and Thornton": "WMBGTRNTN",
    "Williamsburg and Winston": "WMBGWNTN",
    "Winchester and Aspen": "WNCHASP",
    "Winchester and Broadmoor": "WNCHBDMR",
    "Winchester and Brookhaven": "WNCHBKHVN",
    "Winchester and Blackthorn": "WNCHBKTRN",
    "Winchester and Belmore": "WNCHBLMR",
    "Winchester and Barberry": "WNCHBRBY",
    "Winchester and Branch": "WNCHBRCH",
    "Winchester and Cypress": "WNCHCYPS",
    "Winchester and Glenoak": "WNCHGLNK",
    "Winchester and Sumac": "WNCHSMC",
    "Winchester and Southmoor": "WNCHSMR",
    "Winchester and Tamarack": "WNCHTMRK",
    "Windsor and Fields South": "WNDSRFLDS",
    "Windsor and Mullikin": "WNDSRMLKN",
    "Windsor and Staley": "WNDSRSTLY",
    "Wendover and Country Bend": "WNDVRCTRYBND",
    "Wendover and Pebble Creek": "WNDVRPBLCK",
    "Wendover and Summerview": "WNDVRSMRVW",
    "Wendover and Woodspring": "WNDVRWDSPG",
    "Ward and Kerr": "WRDKER",
    "Wright and Beech": "WRTBCH",
    "Wright and Beslin": "WRTBSLN",
    "Wright and Chalmers": "WRTCHAL",
    "Wright and Church": "WRTCHCH",
    "Wright and Columbia": "WRTCLMBA",
    "Wright and Dublin": "WRTDBLN",
    "Wright and Hill": "WRTHIL",
    "Wright and Healey": "WRTHLY",
    "Wright and Springfield": "WRTSPFLD",
    "Wright and Stoughton": "WRTSTOTN",
    "Wright and Washington": "WRTWASH",
    "Westfield and Alton": "WSFLDALTN",
    "Westfield and Carrelton": "WSFLDCRLTN",
    "Westfield and Lawndale": "WSFLDLWNDL",
    "Westfield and Sangamon": "WSFLDSANG",
    "Westfield and Sheridan": "WSFLDSRDN",
    "Westfield and William": "WSFLDWLM",
    "Stephens Family YMCA": "YMCA"
}
