stops = {"U.S. 150 & Dale": "150DALE",
    "U.S. 150 & Dodson": "150DOD",
    "U.S. 150 & University": "150UNI",
    "First & Armory": "1STARY",
    "First & Daniel": "1STDAN",
    "First & Lot E-14": "1STE14",
    "First & Gregory": "1STGRG",
    "First & Gerty": "1STGTY",
    "First & Hazelwood": "1STHZLWD",
    "First at iHotel": "1STIHOTEL",
    "First & Lake Park North": "1STLAKEPKN",
    "First & Lake Park South": "1STLAKEPKS",
    "First & St. Mary's": "1STSMR",
    "First & Stadium": "1STSTDM",
    "First & Windsor": "1STWDSR",
    "Second & Church": "2NDCHCH",
    "Second & Hill": "2NDHILL",
    "Second & Park": "2NDPK",
    "Third & Daniel": "3RDDAN",
    "4th & Armory": "4THARY",
    "Fourth & Armory": "4THARY",
    "Fourth between Kirby & St Marys": "4THBIELFELDT",
    "Fourth & Bradley": "4THBRAD",
    "4th & Chalmers": "4THCHAL",
    "Fourth & Chalmers": "4THCHAL",
    "Fourth & Gregory": "4THGRG",
    "Fourth & Kirby": "4THKBY",
    "Fourth & Pennsylvania": "4THPA",
    "Fourth & Peabody": "4THPDY",
    "Fourth & St. Mary's": "4THSMR",
    "Fifth & Bradley": "5THBRAD",
    "Fifth & Beardsley": "5THBRD",
    "5th & Chalmers": "5THCHAL",
    "Fifth & Columbia": "5THCLMBA",
    "Fifth & Eureka": "5THERKA",
    "Fifth & Grove": "5THGRV",
    "Fifth & Tremont": "5THTRMNT",
    "Fifth & Vine": "5THVIN",
    "5th & Washington": "5THWASH",
    "Fifth & Washington": "5THWASH",
    "Sixth & Armory": "6THARY",
    "Sixth & Bradley": "6THBRAD",
    "Sixth & Chalmers": "6THCHAL",
    "Sixth & Gregory": "6THGRG",
    "Sixth & Peabody": "6THPDY",
    "Anderson & Burkwood": "ADRSNBKWD",
    "Anderson & Brighton": "ADRSNBRTN",
    "Anderson & Colorado": "ADRSNCO",
    "Anderson & Eliot": "ADRSNELIOT",
    "Anderson & Evergreen": "ADRSNEVRGN",
    "Anderson & Fairlawn": "ADRSNFRLN",
    "Anderson & Harding": "ADRSNHRDG",
    "Anderson & Mumford": "ADRSNMFRD",
    "Anderson & Michigan": "ADRSNMI",
    "Anderson & Silver": "ADRSNSLVR",
    "Anderson & Sunnycrest": "ADRSNSNYC",
    "Aldi": "ALDI150",
    "Alpine & Bradley": "ALPBRAD",
    "Alpine & Timberline": "ALPTMBLN",
    "Amber & Myra Ridge": "AMBMYRA",
    "Amber & Philo": "AMBPHILO",
    "Ambucs Park": "AMBUC",
    "Anthony at Ameren": "ANTAMRN",
    "Anthony & Campbell": "ANTCMBL",
    "Anthony & Dale": "ANTDALE",
    "Anthony & Dobbins": "ANTDOBB",
    "Anthony Dr. at Goodwill": "ANTGOODWILL",
    "Anthony at Napleton's": "ANTHNYNAP",
    "Anthony & Willow": "ANTHNYWLLW",
    "Anthony & Columbia": "ANTHYCLMBA",
    "Anthony & Dawn": "ANTHYDAWN",
    "Anthony & Dusk": "ANTHYDUSK",
    "Anthony at Rural King": "ANTHYRK",
    "Anthony at Wood Spring Suites": "ANTHYWSS",
    "Anthony & Kankakee": "ANTKANK",
    "Anthony & Mattis": "ANTMATS",
    "Anthony & North Shore": "ANTNSHR",
    "Anthony & Walters": "ANTWTRS",
    "Airport & Highcross": "APTHICRS",
    "ARC": "ARC",
    "Airport & Arlene": "ARPRTARLNE",
    "Airport & Clifton": "ARPRTCLFTN",
    "Airport & Cunningham": "ARPRTCNGHM",
    "Airport & Captiva": "ARPRTCPTVA",
    "Airport & Donald": "ARPRTDNLD",
    "Airport & Fieldcrest": "ARPRTFDCRST",
    "Airport & Landis Farm": "ARPRTLNDSFRM",
    "Airport & Skyline": "ARPRTSKYLN",
    "Airport & Somerset": "ARPRTSMRST",
    "Airport & Willow": "ARPRTWLLW",
    "Armory & Wright": "ARYWRT",
    "Ashton Woods": "ASHTON",
    "Atrium Apts": "ATRIUM",
    "Baytowne & Boardwalk": "BAYBRDWLK",
    "Beech & Romine": "BCHRMN",
    "Broadmoor & Bellamy": "BDMRBLMY",
    "Broadmoor & Crescent": "BDMRCRSNT",
    "Broadmoor & David": "BDMRDVD",
    "Broadmoor & Galen": "BDMRGLN",
    "Broadmoor & Georgetown": "BDMRGTWN",
    "Broadmoor & Lincoln Pl.": "BDMRLCNPL",
    "Broadmoor & Lynwood": "BDMRLNWD",
    "Broadmoor & Lakeside": "BDMRLSDED",
    "Broadmoor & McDonald": "BDMRMCD",
    "Broadmoor & Robert": "BDMRRBT",
    "Broadway & Bailey": "BDWYBLY",
    "Broadway & Country Club": "BDWYCCR",
    "Broadway & Chapin": "BDWYCHPN",
    "Broadway & Crystal Lake": "BDWYCLD",
    "Save A Lot": "BDWYCM",
    "Broadway & Franklin": "BDWYFRKLN",
    "Broadway & Kerr": "BDWYKER",
    "Broadway & Stebbins": "BDWYLST",
    "Broadway & Oakland": "BDWYOKLN",
    "Broadway & Park": "BDWYPK",
    "Broadway & Thompson": "BDWYTPSN",
    "Broadway & University": "BDWYUNI",
    "Big Lots": "BL",
    "Balboa & Prospect": "BLBOAPSPCT",
    "Balboa & Southwest Dr.": "BLBOASWD",
    "Boulder Ridge & Peppermill": "BLDRRDGPPRML",
    "Boulder Ridge & Farley": "BLDRRGFRLY",
    "Bluegrass & Boca Vista": "BLGRSBCAVSTA",
    "Bluegrass & Boulder Ridge": "BLGRSBLDRRDG",
    "Bluegrass & Brookfield": "BLGRSBRKFLD",
    "Bluegrass & Summersage": "BLGRSSMRSG",
    "Bluegrass & Sandstone": "BLGRSSNDSTN",
    "": "BLOM	Bloomington & Mittendorf",
    "Bloomington & Alabama": "BLOMAL",
    "Bloomington & Prospect": "BLOMHD",
    "Bloomington & Hagan": "BLOMHGN",
    "Bloomington & Highland": "BLOMHILND",
    "Bloomington & Louisiana": "BLOMLA",
    "Bloomington & McKinley": "BLOMMCNLY",
    "Bloomington at Pioneer Plaza": "BLOMPNR",
    "Bloomington & Prospect": "BLOMPSPCT",
    "Bloomington & Sunset": "BLOMSNST",
    "Bloomington & Willis": "BLOMWLS",
    "Bonnie Blair & Amy": "BNBLRAMY",
    "Bonnie Blair & Gold Medal": "BNBLRGDMD",
    "Bonnie Blair & Nancy Beth": "BNBLRNNBTH",
    "Bonnie Blair & Sharon": "BNBLRSHRN",
    "Bonnie Blair & Valerie": "BNBLRVLR",
    "Brownfield & Agnes": "BNFLDAGNS",
    "Brownfield & Airport": "BNFLDAPT",
    "Brownfield & Arlene": "BNFLDARL",
    "Brownfield & Clifton": "BNFLDCFTN",
    "Brownfield & Columbia": "BNFLDCLMBA",
    "Brownfield & Johnson": "BNFLDJHN",
    "Brownfield & Mary Lou": "BNFLDML",
    "Brownfield & Perkins": "BNFLDPKNS",
    "Brownfield & Prairieview": "BNFLDPRVW",
    "Brownfield & Sharlyn": "BNFLDSLYN",
    "Bentbrook & Bentbrook Ct": "BNTBRKBBCT",
    "Bentbrook & Cobblefield": "BNTBRKCBLFLD",
    "Bentbrook & Golf Creek": "BNTBRKGLFCRK",
    "Bentbrook & Pinecrest": "BNTBRKPNCRST",
    "Bentbrook & Riverknoll": "BNTBRKRVRKNL",
    "Bentbrook & Staley": "BNTBRKSTLY",
    "Bradley": "BRAD",
    "Bradley & Country Fair Dr.": "BRADCFD",
    "Bradley & Clayton": "BRADCLTN",
    "Bradley & Champaign": "BRADCMI",
    "Bradley & Crispus": "BRADCRPS",
    "Bradley & Carver": "BRADCRVR",
    "Bradley & Duncan": "BRADDNCN",
    "Bradley & Elm": "BRADELM",
    "Bradley & Garden Hills": "BRADGH",
    "Bradley & Hagan": "BRADHGN",
    "Bradley & Hickory": "BRADHKRY",
    "Bradley & James": "BRADJAS",
    "Bradley & Mattis": "BRADMATS",
    "Bradley & McKinley": "BRADMCNLY",
    "Bradley & Neil": "BRADNEIL",
    "Bradley & Prospect": "BRADPSPCT",
    "Bradley & Redwood": "BRADRDWD",
    "Bradley & State": "BRADSTE",
    "Bradley & Walnut": "BRADWLNT",
    "Bradley & Willis": "BRADWLS",
    "BRADWMBG": "BRADWMBG",
    "Bradley & Williamsburg": "BRADWMBG",
    "Bardeen & Toalson": "BRDNTLSN",
    "Boardwalk & Interstate": "BRDWLKINT",
    "Boardwalk & Meijer Dr.": "BRDWLKMJR",
    "Boardwalk & Town Center": "BRDWLKTCB",
    "Brady & High": "BRDYHI",
    "Brittany Trail & Kensington Knoll": "BRTTRLKNTNKNL",
    "Brittany Trail & Mullikin": "BRTTRLMLKN",
    "Brittany Trail & Southford": "BRTTRLSTHFRD",
    "Brittany Trail & Southford Trace W": "BRTTRLSTHFRDTR",
    "Brittany Trail & Staley": "BRTTRLSTLY",
    "Burwash & Woodfield": "BRWSWDFLD",
    "Beslin & Romine": "BSLNRMN",
    "Butzow & Lierman": "BTSLRMN",
    "Carroll at CACC": "CACC",
    "Campus Circle": "CAMPUSCIR",
    "Country Brook": "CB",
    "Cobblefield & Aberdeen": "CBLFDABDN",
    "Cobblefield & Bridge Point Dr": "CBLFLDBDGPT",
    "Cobblefield & Balmoral": "CBLFLDBLML",
    "Cobblefield & Crail": "CBLFLDCRL",
    "Cobblefield & Englewood": "CBLFLDEGLWD",
    "Cobblefield & Glenn Brooke": "CBLFLDGLNBRK",
    "Cobblefield & Inverness": "CBLFLDINV",
    "Colbert Park": "CBRTPK",
    "Country Club Rd. at Apts.": "CCRAPTS",
    "Country Club & Division": "CCRDVSN",
    "Country Club & Golfview": "CCRGFVW",
    "Country Club & Willow": "CCRWLLW",
    "County Satellite Jail": "CCSJ",
    "Central High": "CE",
    "Central High": "CENTRAL",
    "Country Fair": "CF",
    "Country Fair Dr. & Camp": "CFDCAMP",
    "Country Fair Dr. & Church": "CFDCHCH",
    "Country Fair Dr. & Cone": "CFDCONE",
    "Country Fair Dr. at Fluid Events": "CFDFLDEV",
    "Country Fair Dr. & Park": "CFDPK",
    "Country Fair Dr. at R.P. Lumber": "CFDRP",
    "Springfield & Country Fair Dr.": "CFDSPFLD",
    "Social Security": "CFDSSI",
    "Country Fair Dr. & University": "CFDUNI",
    "Country Fair West Entrance": "CFW",
    "Church St.": "CHCH",
    "Church & Busey": "CHCHBUSY",
    "Church & Carson": "CHCHCRSN",
    "Church & Denton": "CHCHDNTN",
    "Church & Draper": "CHCHDRPR",
    "Church & Edwin": "CHCHEDWN",
    "Church & Elm": "CHCHELM",
    "Church & Fair": "CHCHFAIR",
    "Church & Garfield": "CHCHGRFLD",
    "Church & James": "CHCHJAS",
    "Church & Lynn": "CHCHLYN",
    "Church & Mattis": "CHCHMATS",
    "Church & McKinley": "CHCHMCNLY",
    "Church & Miller": "CHCHMLR",
    "Church & Neil": "CHCHNEIL",
    "Church & New": "CHCHNEW",
    "Church & Orchard": "CHCHORCD",
    "Church & Prairie": "CHCHPRRE",
    "Church & Prospect": "CHCHPSPCT",
    "Church & Russell": "CHCHRSL",
    "Church & State": "CHCHSTE",
    "Church & Victor": "CHCHVCTR",
    "Church & Willis": "CHCHWLS",
    "Chemical & Life Sciences": "CHEMLS",
    "Cherry Hills & Applewood": "CHHLAPLWD",
    "Cherry Hills & Coppertree": "CHHLCPRTRE",
    "Cherry Hills & Curtis": "CHHLCTS",
    "Cherry Hills & Lakeview": "CHHLLKVW",
    "Cherry Hills & Pine Valley": "CHHLPNVY",
    "Cherry Hills & Crestridge": "CHHLSCSTRG",
    "Columbia & Betsy Ross": "CLMBABTSYRS",
    "Columbia & Hickory": "CLMBAHKRY",
    "Columbia & Hancock": "CLMBAHNK",
    "Coler & Church": "CLRCHCH",
    "Coler & Fairview": "CLRFRVW",
    "Clayton & Bellerieve": "CLTNBLRV",
    "Clayton & Clearwater": "CLTNCLW",
    "Clayton & Compton": "CLTNCPT",
    "Clayton & Creve Coeur": "CLTNCRVCR",
    "Clayton & Crestview": "CLTNCSV",
    "Clayton & Covington": "CLTNCVT",
    "Clayton & Delmar": "CLTNDLMR",
    "Clayton & Duncan": "CLTNDNCN",
    "Clayton & Higgins": "CLTNHGN",
    "Clayton & Hilltop": "CLTNHLT",
    "Clayton & Heritage": "CLTNHTG",
    "Clayton & High View": "CLTNHV",
    "Clayton & Irvine": "CLTNIRVN",
    "Clayton & Pomona": "CLTNPMNA",
    "Clayton & Rossmoor": "CLTNRSM",
    "Campbell & Aztec": "CMBLAZTEC",
    "Campbell & Comanche": "CMBLCMCHE",
    "Campbell & Curt": "CMBLCRT",
    "Campbell & Dobbins": "CMBLDBNS",
    "Campbell & Queensway": "CMBLQNWAY",
    "Campbell & Roland": "CMBLRLND",
    "Champaign House": "CMIHS",
    "Cunningham & Crystal Lake": "CNHMCLD",
    "Cunningham & Oakland": "CNHMOKLN",
    "Cunningham & Park": "CNHMPK",
    "Cunningham & Perkins": "CNHMPKNS",
    "Cunningham & Thompson": "CNHMTPSN",
    "Convenience Dr. & Market": "CNVMKT",
    "County Market": "COCM",
    "Colorado & Larch": "COLRCH",
    "Copper Ridge & Blackhawk": "CPRRDGBLKHK",
    "Copper Ridge & Copper": "CPRRDGCPR",
    "Copper Ridge & Ironwood": "CPRRDGIRNWD",
    "Copper Ridge & Mullikin": "CPRRDGMLKN",
    "Copper Ridge & Sand": "CPRRDGSND",
    "Cyprus Point & Stillwater Landing": "CPRSPTSTLWTR",
    "Captiva & George": "CPTVAGRG",
    "Captiva & Northwood": "CPTVANRTHWD",
    "Captiva & Sanibel": "CPTVASNBL",
    "Coronado & Dover": "CRNDODVR",
    "Coronado & Ventura": "CRNDOVTRA",
    "Carroll": "CROL",
    "Carrol Fire Department": "CROLFD",
    "Carroll & Kerr": "CROLKER",
    "Crossgate & Charwick": "CRSGTCHWK",
    "Crossgate & Crossgate Ct.": "CRSGTCRSGTCT",
    "Crossgate & Ironwood Ln": "CRSGTIRNWD",
    "Crescent & Greendale": "CRSNTGRNDL",
    "Jefferson Middle School": "CRSNTJMS",
    "Crescent & John": "CRSNTJOHN",
    "Crescent & Lawndale": "CRSNTLWNDL",
    "Crescent & Ola": "CRSNTOLA",
    "Crescent & Parkdale": "CRSNTPKDL",
    "Round Barn Manor": "CRSNTRBM",
    "Crescent & Round Barn": "CRSNTRBR",
    "Crescent & Rodney": "CRSNTROD",
    "Crescent & Sangamon": "CRSNTSANG",
    "Crescent & Southwood": "CRSNTSWD",
    "Crescent & William": "CRSNTWLM",
    "Crestridge & Lakewood": "CRSTRGLKWD",
    "Crestwood & Bradley": "CRSTWDBRAD",
    "Crestwood & Clayton": "CRSTWDCLTN",
    "Crestwood & Edward Hoffman": "CRSTWDEDHFMN",
    "Crestwood & Florence": "CRSTWDFLNC",
    "Crestwood & Katie Lynn": "CRSTWDKTLYN",
    "Crestwood & Ladue": "CRSTWDLDU",
    "Curtis & Wynstone": "CRTSWNSTN",
    "Country Squire Ct.": "CSQRCT",
    "Country Squire & Kinch": "CSQRKNCH",
    "Cottage Grove & Brighton": "CTGRVBRITN",
    "Cottage Grove & California": "CTGRVCA",
    "Cottage Grove & Colorado": "CTGRVCO",
    "Cottage Grove & Crestwood": "CTGRVCRWD",
    "Cottage Grove & Eastern": "CTGRVERN",
    "Cottage Grove & Glenwood Oaks": "CTGRVGNWD",
    "Cottage Grove & Green": "CTGRVGRN",
    "Cottage Grove & Harding": "CTGRVHRDG",
    "Cottage Grove & Illinois": "CTGRVIL",
    "Cottage Grove & Mitchem": "CTGRVMCHM",
    "Cottage Grove & Oregon": "CTGRVOR",
    "Cottage Grove & Penn": "CTGRVPA",
    "Cottage Grove & Philo": "CTGRVPHILO",
    "Cottage Grove & Washington": "CTGRVWASH",
    "Country Bend & Springhill": "CTRYBNDSPGHL",
    "Country Bend & Summerhill": "CTRYBNDSUMHL",
    "Curtis & First": "CTS1ST",
    "Curtis & Meadow": "CTSMDW",
    "Curtis Meadow & Brighton": "CTSMDWBRTN",
    "Curtis Meadow & Foxborough": "CTSMDWFXBRGH",
    "Curtis Meadow & Staley": "CTSMDWSTLY",
    "Curtis Rd. at Winfield Village": "CTSWIN",
    "Public Health District": "CUPHD",
    "Coventry & Maynard": "CVTRYMYNRD",
    "Coventry & Roxford": "CVTRYRXFRD",
    "DART": "DART",
    "Devonshire Corporate Center": "DCC",
    "Dodson & Illinois": "DDSNIL",
    "Dodson & Nevada": "DDSNNV",
    "Dodson & Washington": "DDSNWASH",
    "age": "DEPOT",
    "Duncan & Blair": "DNCNBLR",
    "Duncan & Clark": "DNCNCLKRD",
    "Duncan & Clayton": "DNCNCLTN",
    "Duncan & Crossing Ct.": "DNCNCRSNG",
    "Duncan & Crestridge": "DNCNCSTRG",
    "Duncan & Daniel": "DNCNDNL",
    "Duncan & Lager": "DNCNLGR",
    "Duncan & Lawndale": "DNCNLWNDL",
    "Duncan & Meadows West": "DNCNMWW",
    "Duncan & Prairie Meadow": "DNCNPMDW",
    "Duncan & Ridgewood": "DNCNRDGWD",
    "Duncan & Rolling Acres": "DNCNRLACR",
    "Duncan & Sierra": "DNCNSRA",
    "Duncan & Stoneybrook": "DNCNSTNBK",
    "Duncan & Southwood": "DNCNSWOOD",
    "Duncan & Valerie": "DNCNVLR",
    "Duncan & Valleybrook": "DNCNVYBK",
    "Dorner & Peabody": "DNRPDY",
    "Dodson East & Slayback": "DODSLYBK",
    "Development Services Center": "DSC",
    "D.S.C. on Clark": "DSCCLK",
    "Devonshire & Devonshire Ct.": "DVNDVNCT",
    "Devonshire & Lynnwood Dr.": "DVNLNWD",
    "Devonshire & Lakeside": "DVNLSDED",
    "Devonshire & Mayfair": "DVNMYFR",
    "Devonshire & Noel": "DVNNL",
    "Devonshire & Peach": "DVNPCH",
    "Devonshire & Sandpiper": "DVNSNPR",
    "Dover & Balboa": "DVRBLBOA",
    "Lot E-14": "E14",
    "Eastern": "EAST",
    "Eastern & Kerr": "EASTKER",
    "Elm & Park": "ELMPK",
    "Elm & Vine": "ELMVIN",
    "Edison Middle School": "EMS",
    "FAR": "FAR",
    "Fedex on Killarney": "FEDEXA",
    "Florida & Adams": "FLADAMS",
    "Florida & Anderson": "FLADRSN",
    "Florida & Broadway": "FLBRDWY",
    "Florida & Bermuda": "FLBRMD",
    "Florida & Busey": "FLBUSEY",
    "Florida & Carle": "FLCARLE",
    "Florida & Curtiss": "FLCRTS",
    "Florida & Cottage Grove": "FLCTGRV",
    "Fields South & Farhills": "FLDSFRHL",
    "Fieldstone at Horizon Hobby": "FLDSTNHH",
    "Fieldstone at Metritech": "FLDSTNMETRI",
    "Florida & Florida Ct.": "FLFLCT",
    "Florida & Florida Dr.": "FLFLDR",
    "Florida & Grove": "FLGRV",
    "Florida & Hillcrest": "FLHLCRST",
    "Florida & James Cherry": "FLJASCHER",
    "Florida & Kinch": "FLKNCH",
    "Florida & Lincolnwood": "FLLCLNWD",
    "Florida & Lincoln": "FLLNCLN",
    "Florida & Linden": "FLLNDN",
    "Florida & Maple": "FLMPL",
    "Florida & Orchard": "FLOD",
    "Florida & Philo": "FLPHILO",
    "Florida & Pleasant": "FLPLSNT",
    "Florida & Race": "FLRACE",
    "Florida & Rutledge": "FLRTLG",
    "Florida & Smith": "FLSMITH",
    "Sunnycrest Mall": "FLSUN",
    "Florida at Thomas Paine": "FLTOMPAINE",
    "Florida & Vine": "FLVIN",
    "Florida & Wiley": "FLWLY",
    "Fox at Community Elements": "FOXCE",
    "Fox at Christie Clinic": "FOXCHRSTIE",
    "Fox & Devonshire": "FOXDVN",
    "Fox & Knollwood": "FOXKLWD",
    "Fox at Remax": "FOXREMAX",
    "Fox & State": "FOXSTE",
    "Fox at SURS": "FOXSURS",
    "Fox & Windsor": "FOXWDSR",
    "Farber at CERL": "FRBRCERL",
    "Farber & Newton": "FRBRNWTN",
    "Farhills & Staley": "FRHLSTLY",
    "Fairlawn": "FRLN",
    "Fairlawn & Cottage Grove": "FRLNCTGRV",
    "Fairlawn & Eastern": "FRLNERN",
    "Fairlawn & Grant Pl.": "FRLNGRNT",
    "Fairlawn & Patton": "FRLNPTN",
    "Farley & Pebblebrook": "FRLYPBLBRK",
    "Farley & West Ridge": "FRLYWRDG",
    "Fairview & Busey": "FRVWBUSEY",
    "Fairview & Gregory": "FRVWGRG",
    "Fairview & Goodwin": "FRVWGWN",
    "Fairview & Harvey": "FRVWHRVY",
    "Fairview & Lincoln": "FRVWLNCLN",
    "Fairview & Linview": "FRVWLNVW",
    "Foothill & Robert": "FTHLRBT",
    "Ginger Creek": "GC",
    "Goodwin at Ceramics Building": "GDWNCB",
    "Goodwin at Materials Research": "GDWNMRL",
    "George Huff & Race": "GHFRACE",
    "Galen & Devonshire": "GLNDVN",
    "Galen & Harrington": "GLNHRTN",
    "Galen & Newbury": "GLNNWBY",
    "Galen & Plymouth": "GLNPLMT",
    "Galen & Ross": "GLNROSS",
    "Galen & Salisbury": "GLNSLBY",
    "Galen & Sussex": "GLNSSX",
    "Galen & Theodore": "GLNTDR",
    "Galen & Windsor": "GLNWDSR",
    "Galen & Wilshire": "GLNWLSH",
    "Galen & Yorkshire": "GLNYKSH",
    "Butzow at Guardian West": "GRD",
    "Guardian Dr. & Butzow": "GRDBTZ",
    "Gregory & Dorner": "GRGDNR",
    "Gregory at Ikenberry Commons": "GRGIKE",
    "Gregory at Library": "GRGLIB",
    "Gregory at Mumford Hall": "GRGMUM",
    "Green & Second": "GRN2ND",
    "Green & Fourth": "GRN4TH",
    "Green & Sixth": "GRN6TH",
    "Green & Anderson": "GRNADRSN",
    "Green & Birch": "GRNBRCH",
    "Green & Busey": "GRNBUSEY",
    "Green & Cedar": "GRNCDR",
    "Green & Gregory": "GRNGRGST",
    "Green & Grove": "GRNGRV",
    "Green & Goodwin": "GRNGWN",
    "Green & Johnson": "GRNJNSN",
    "Green & Locust": "GRNLCST",
    "Green & Lynn": "GRNLYN",
    "Green & Mathews": "GRNMAT",
    "Green & Maple": "GRNMPL",
    "Green & Neil": "GRNNEIL",
    "Green & Orchard": "GRNORCH",
    "Green & Prairie": "GRNPRRE",
    "Green & Prospect": "GRNPSPCT",
    "Green & Race": "GRNRACE",
    "Green & Randolph": "GRNRNDLF",
    "Green & State": "GRNSTE",
    "Green & Urbana": "GRNUBNA",
    "Green & Webber": "GRNWBR",
    "Green & Wright": "GRNWRT",
    "Goodwin & Church": "GWNCHCH",
    "Goodwin & Clark": "GWNCLK",
    "Goodwin & Gregory": "GWNGRG",
    "Goodwin & Hill": "GWNHIL",
    "Goodwin & Main": "GWNMN",
    "Goodwin & Nevada": "GWNNV",
    "Goodwin & Park": "GWNPK",
    "Holiday Inn": "HDYINN",
    "Hagan & Dennison": "HGNDNSN",
    "Hagan & Pioneer": "HGNPNR",
    "Highcross & Apostalic Life Church": "HICRSALC",
    "Highcross & Bruce Acres": "HICRSBA",
    "Highcross & Nordland": "HICRSNDLD",
    "Halifax & Maynard": "HLFXMYNRD",
    "Hamilton & Betsy Ross": "HMLTNBTSYRS",
    "Hamilton & Jefferson": "HMTNJFSN",
    "Hancock & Hamilton": "HNKHMTN",
    "Hancock & Liberty": "HNKLBRTY",
    "Hunter & Austin": "HNTRASTN",
    "Hunter & Country Squire": "HNTRCSQR",
    "Hunter & Lanore": "HNTRLNR",
    "Steer Place": "HRDGSTP",
    "Harris & Alabama": "HRISAL",
    "Harris & Bloomington": "HRISBLOM",
    "Harris & Bradley": "HRISBRAD",
    "Harris & Beardsley": "HRISBRD",
    "Franklin Middle School": "HRISFMS",
    "Harris & Harvard": "HRISHRVRD",
    "Harris & Louisiana": "HRISLA",
    "Harris & Maple": "HRISMPL",
    "Harris & Sherwood": "HRISSHWD",
    "Heritage Park": "HRTGPK",
    "Hessel & Randolph": "HSLRNDLF",
    "Hazelwood & Oak": "HZLWDOAK",
    "I.E.T.C.": "IETC",
    "I.E.T.C. & Mattis": "IETCMATS",
    "Independent Living": "ILAPTS",
    "Illinois & Broadway": "ILBDWY",
    "Illinois & Glenn": "ILGLN",
    "The Place at 117": "INDIGO",
    "Independence & Betsy Ross": "INDPNCBTSYRS",
    "Interstate & Waterview Way": "INTERSTWW",
    "Interstate & Farber": "INTFRBR",
    "Interstate & Newmark": "INTNWMK",
    "Interstate & Research": "INTRSRCH",
    "Interstate Dr. at Walmart": "INTWALMART",
    "Inverness & Prestwick Pt": "INVPSTWK",
    "Ironwood & Staley": "IRNWDSTLY",
    "Illinois St. Residence Hall": "ISR",
    "Water Survey": "ISWS",
    "Illinois Terminal": "IT",
    "I. T. at Market St.": "ITMKT",
    "Illini Union": "IU",
    "Jefferson & Columbia": "JFSNCLMBA",
    "Jefferson Middle School": "JMS",
    "John & Chicago": "JOHNCHI",
    "John & Dogwood": "JOHNDGWD",
    "John & Duncan": "JOHNDNCN",
    "John & Draper": "JOHNDRPR",
    "John & Edwin": "JOHNEDWN",
    "John & Elm": "JOHNELM",
    "John & Fair": "JOHNFAIR",
    "John & Foley": "JOHNFOLY",
    "John & Frank": "JOHNFRANK",
    "John & Goldenview": "JOHNGLDVW",
    "John & Garfield": "JOHNGRFLD",
    "John & Highland": "JOHNHILND",
    "John & Hollycrest": "JOHNHLYCST",
    "John & James": "JOHNJAS",
    "John & Kenwood": "JOHNKNWD",
    "John & Lynn": "JOHNLYN",
    "John & Mattis": "JOHNMATS",
    "John & Mitchell Ct.": "JOHNMCHLCT",
    "John & McKinley": "JOHNMCNLY",
    "John & New": "JOHNNEW",
    "John & Pine": "JOHNPINE",
    "John & Prairie": "JOHNPRRE",
    "John & Prospect": "JOHNPSPCT",
    "John & Ridgeway": "JOHNRGWAY",
    "John & Russell": "JOHNRSL",
    "John & Victor": "JOHNVCTR",
    "John & Willis": "JOHNWILS",
    "John & Westlawn": "JOHNWLWN",
    "John & Western": "JOHNWSTRN",
    "Japan House": "JPN",
    "Kirby & Alma": "KBYALMA",
    "Kirby & Arrow": "KBYARW",
    "Kirby & Bellepark": "KBYBLPK",
    "Kirby & Carolyn": "KBYCAROL",
    "Kirby & Cobblefield": "KBYCBLFLD",
    "Kirby & Cambridge": "KBYCMBG",
    "Kirby & Carriage Way": "KBYCRGWY",
    "Kirby & Coronado": "KBYCRNDO",
    "Kirby & Crescent": "KBYCRSNT",
    "Kirby & Duncan": "KBYDNCN",
    "Kirby & Dodds": "KBYDODD",
    "Kirby & Dawson": "KBYDWSN",
    "Kirby & Grandview": "KBYGDVWW",
    "Kirby & Grandview West": "KBYGDVWW",
    "Kirby & Greencroft": "KBYGRNCFT",
    "Kirby & Kenwood": "KBYKNWD",
    "Kirby & Lincoln Rd.": "KBYLCLNRD",
    "Kirby & Mattis": "KBYMATS",
    "Kirby & Mayfair": "KBYMYFR",
    "Kirby & Neil": "KBYNEIL",
    "Kirby & Oak": "KBYOAK",
    "Kirby & Park Haven": "KBYPRKHVN",
    "Kirby & Ridge": "KBYRDGRD",
    "Kirby & Rose": "KBYROSE",
    "Kirby & Rose": "KBYRSWD",
    "Kirby & Rosewood": "KBYRSWD",
    "Kirby & Scottsdale": "KBYSCTDL",
    "Kirby & Stratford": "KBYSRTFRD",
    "Kirby & State": "KBYSTE",
    "Kirby & Valley Rd.": "KBYVYRD",
    "Kirby & Waverly": "KBYWAVE",
    "Kirby & Westfield": "KBYWSFLD",
    "Kirby & Western": "KBYWSTRN",
    "Kerr & Berkley": "KERBRKLY",
    "Kerr & Cunningham": "KERCNHM",
    "Kerr & Carroll": "KERCROL",
    "Kerr & Division": "KERDVSION",
    "Kerr & Geraldine": "KERGRLDNE",
    "Kerr & Highlands": "KERHGHLNDS",
    "Kerr & Ward": "KERWRD",
    "Kinch & Easy": "KNCHEASY",
    "Kinch & Lantern Hill": "KNCHLH",
    "Kinch & Rainbow View": "KNCHRAIN",
    "Kenyon & Cracker Barrel": "KNYNCRKRB",
    "Kenyon at Eastland Suites": "KNYNESTLND",
    "Kenyon at Steak & Shake": "KNYNSTKSHK",
    "Kettering & Linview": "KPDLNVW",
    "Krannert Center": "KRANNERT",
    "Kirby & Glenshire": "KRBYGLNSHR",
    "Kirby & Mullikin": "KRBYMLKN",
    "LAR": "LAR",
    "Liberty & Betsy Ross": "LBRTYBTSYRS",
    "Liberty & Columbia": "LBRTYCLMBA",
    "Liberty & Jefferson": "LBRTYJEF",
    "St. Mathews": "LCNSR",
    "Lincolnshire & Foothill": "LCNSRFTHL",
    "Leggett & Bardeen": "LGGTBRDN",
    "Logan & First": "LGN1ST",
    "Lakeview & Wedgewood": "LKVWWGWD",
    "Lakeview & Worthington": "LKVWWTGTN",
    "Lincoln & Anthony": "LNCLNANT",
    "Lincoln & Bradley": "LNCLNBRAD",
    "Lincoln & College Ct.": "LNCLNCC",
    "Lincoln & Church": "LNCLNCHCH",
    "Lincoln & Delaware": "LNCLNDE",
    "Lincoln & Eads": "LNCLNEADS",
    "Lincoln & Florida": "LNCLNFL",
    "Lincoln & Hill": "LNCLNHIL",
    "Lincoln & Illinois": "LNCLNIL",
    "Lincoln & Kettering Park": "LNCLNKING",
    "Lincoln & Killarney": "LNCLNKLRNY",
    "Lincoln & Oregon": "LNCLNOR",
    "Lincoln & Pennsylvania": "LNCLNPA",
    "Lincoln & Park": "LNCLNPK",
    "Lincoln & St. Mary's": "LNCLNSMR",
    "Lincoln & St. Marys": "LNCLNSMR",
    "Lincoln & Sunset": "LNCLNSNST",
    "Lincoln & Vermont": "LNCLNVT",
    "Lincoln & Wascher": "LNCLNWSCR",
    "Lyndhurst & Lyndhurst Village Ct.": "LNHSTARBR",
    "Lyndhurst & Arbour": "LNHSTARBR1",
    "Lyndhurst & Bedford": "LNHSTBDFD",
    "Lyndhurst & Burwash": "LNHSTBRWS",
    "Lyndhurst & Evergreen Circle": "LNHSTEGRN",
    "Lyndhurst & Lyndhurst Village Ct.": "LNHSTLNVCT",
    "Lyndhurst & Magnolia": "LNHSTMAGN",
    "Lyndhurst & Old Maple Lane": "LNHSTOML",
    "Lyndhurst & Park Ln": "LNHSTPKLN",
    "Linview & Killarney": "LNVWKLRNY",
    "Lierman & Bartell": "LRMNBRTL",
    "Lierman & Hunter": "LRMNHNTR",
    "Lakeshore & Maynard": "LSDMYNRD",
    "Lincoln Square Courthouse": "LSE",
    "Lincoln Square Garage East": "LSE",
    "Lincoln Square Garage South": "LSE",
    "Lawndale & Bellepark": "LWNDLBLPK",
    "Lawndale & Centennial": "LWNDLCENT",
    "Lynn & Park": "LYNPRK",
    "Mattis & Alton": "MATSALTN",
    "Mattis & Anita": "MATSANTA",
    "Mattis & Broadmoor": "MATSBDMR",
    "Mattis & Bloomington": "MATSBLOM",
    "Mattis & Branch": "MATSBRCH",
    "Mattis & Chevy Chase": "MATSCHEVY",
    "Mattis & Cypress": "MATSCYPS",
    "Mattis & Devonshire": "MATSDVN",
    "Mattis & Glenn Park": "MATSGLNPK",
    "Mattis & Gentry Square South": "MATSGNSQ",
    "Mattis & Henry": "MATSHNRY",
    "Mattis & Harbor Point": "MATSHRBR",
    "Mattis & Interstate": "MATSINT",
    "Mattis & Ivy Ct. North": "MATSIVYN",
    "Mattis & Ivy Ct. South": "MATSIVYS",
    "Mattis & Meadow": "MATSMDWDR",
    "Mattis North Apartments": "MATSMNA",
    "Mattis & Princeton": "MATSPRNCTN",
    "Mattis & Round Barn": "MATSRBR",
    "Mattis & Sangamon": "MATSSANG",
    "Mattis & Sheridan": "MATSSHRDN",
    "Mattis & Sumac": "MATSSMC",
    "Mattis & Southwood": "MATSSTHWD",
    "Mattis & Stonegate": "MATSSTNGT",
    "Mattis at Post Office": "MATSUSPS",
    "Mattis & Windsor": "MATSWDSR",
    "Mattis & William": "MATSWLM",
    "McKinley & Beardsley": "MCNLYBRD",
    "McKinley & Eureka": "MCNLYERKA",
    "McKinley & Harvard": "MCNLYHVAD",
    "McKinley & Maple": "MCNLYMPL",
    "McKinley & Tremont": "MCNLYTRMNT",
    "MacArthur & California": "MCRTRCA",
    "MacArthur & MacArthur Ct.": "MCRTRCT",
    "MacArthur & High": "MCRTRHI",
    "MacArthur & Illinois": "MCRTRIL",
    "Meijer Dr. at Meijer": "MEIJER",
    "Mercury & Apollo": "MERCAPLO",
    "Mercury at FedEx": "MERCFEDEX",
    "Mercury & Gemini": "MERCGEMCT",
    "McHenry & Anderson": "MHRYADRSN",
    "McHenry & Combes": "MHRYCMBS",
    "McHenry & Cottage Grove": "MHRYCTGRV",
    "McHenry & Fletcher": "MHRYFLCHR",
    "McHenry & Lynn": "MHRYLYN",
    "McHenry & Lynn St. 1": "MHRYLYN1",
    "McHenry & Lynn St. #2": "MHRYLYN2",
    "McHenry & Lynn - East": "MHRYLYNE",
    "McHenry & Philo": "MHRYPHILO",
    "McHenry & Pond": "MHRYPND",
    "McHenry & Vawter": "MHRYVWTR",
    "Michigan & Green Ridge": "MIGRNRDG",
    "Michigan & Kinch": "MIKNCH",
    "Michigan & Smith": "MISMITH",
    "Meijer Drive & Prospect": "MJRPSPCT",
    "Market Place and Wilbur": "MKPLCWLB",
    "Market & Bellefontaine": "MKTBELL",
    "Barnes & Noble Books": "MKTBNB",
    "Market & Bradley": "MKTBRAD",
    "Market & Garwood": "MKTGAR",
    "Market & Kenyon": "MKTKNYN",
    "Market & Logan": "MKTLGN",
    "Market & Mercury": "MKTMERC",
    "Market & Marketview": "MKTMKTV",
    "Market & Paul": "MKTPAUL",
    "Market & Peach Tree": "MKTPCH",
    "Market Place": "MKTPLC",
    "Market Place & Convenience Dr.": "MKTPLCCD",
    "Market Place North Entrance": "MKTPLCN",
    "Mkt Plc North Ent. & Market": "MKTPLCNMKT",
    "Market Place South": "MKTPLCS",
    "Market Place Southeast": "MKTPLCSE",
    "Market Place West": "MKTPLCW",
    "Market & Roper": "MKTRPR",
    "Market & Tulip Tree": "MKTTLP",
    "Marketview at Marketview Center": "MKTV",
    "Marketview & Anthony": "MKTVANT",
    "Marketview at Sams": "MKTVSAMS",
    "Market & Wallace": "MKTWLACE",
    "Market & Wilbur": "MKTWLBR",
    "Mullikin & Copper Ridge": "MLKNCPRRG",
    "Mullikin & Crossgate": "MLKNCRSGT",
    "Mullikin & Curtis Meadow": "MLKNCTSMDW",
    "Mullikin & Doverbrook": "MLKNDVRBRK",
    "Mullikin & Graves Ct.": "MLKNGRVCT",
    "Mullikin & Ironwood": "MLKNIRNWD",
    "Mullikin & Remington Way": "MLKNRMGNTN",
    "Mullikin & Stonebridge": "MLKNSTNBDG",
    "Mullikin & Trostshire": "MLKNTRSTSHR",
    "Mullikin & Villa": "MLKNVLA",
    "Mullikin & Westborough": "MLKNWSTBRGH",
    "Main & University": "MN150",
    "Main & Art Bartell": "MNABD",
    "Main & Broadway": "MNBRDWY",
    "Main & Brady": "MNBRDY",
    "Main & Chestnut": "MNCHSNT",
    "Main & Cottage Grove": "MNCTGRV",
    "Main & Dodson": "MNDDSN",
    "Main & Dewey": "MNDWY",
    "Main & Ennis": "MNENIS",
    "Main & Fremont": "MNFREMNT",
    "Main & Glover": "MNGLVR",
    "Main & Grossbach": "MNGRSBCH",
    "Main & Grove": "MNGRV",
    "Main & Hartle": "MNHTL",
    "Main at ILEAS": "MNILEAS",
    "Main & Lierman": "MNLRMN",
    "Main & Lynn": "MNLYN",
    "Main & Maple": "MNMPL",
    "Main & Poplar": "MNPLR",
    "Main & Scottswood": "MNSCWD",
    "Main & Smith": "MNSMITH",
    "Main & Urbana": "MNUBNA",
    "Main & Vine": "MNVIN",
    "Main & Webber": "MNWBR",
    "Main & Walnut": "MNWLNT",
    "Maplepark & Lawndale": "MPLPKLWNDL",
    "Maplepark & Maplewood": "MPLPKMPLWD",
    "Maplepark & Sangamon": "MPLPKSANG",
    "Maplepark & William": "MPLPKWLM",
    "Moraine & Lake Shore": "MRANLSD",
    "Mattis & Green": "MTSGRN",
    "Mattis & Healey": "MTSHLY",
    "Mayfair & Broadmoor": "MYFRBDMR",
    "Mayfair & Georgetown": "MYFRGTOWN",
    "Mayfair & Lincolnshire": "MYFRLCLNSH",
    "Mayfair & Old Farm": "MYFROF",
    "Mayfair & Sandpiper": "MYFRSNFR",
    "Mayfair & Theodore": "MYFRTDR",
    "Mayfair & Weathervane": "MYFRWTRVN",
    "Maynard & Coventry": "MYNDCVTRY",
    "Myra Ridge & Autumn Ridge": "MYRAAUTM",
    "Myra Ridge & Ridge Park": "MYRARGPK",
    "Myra Ridge & Silver Hill": "MYRASLVHL",
    "Myra Ridge & Trails": "MYRATRLS",
    "Neil & Anthony": "NEILANT",
    "Neil & Arcadia": "NEILARC",
    "Neil & Bellefontaine": "NEILBELL",
    "Neil & Beardsley": "NEILBRD",
    "Neil & Burwash": "NEILBRWS",
    "Neil & Center Dr.": "NEILCD",
    "Neil & Columbia": "NEILCLMBA",
    "Neil & Center": "NEILCNTR",
    "Neil & Edgebrook": "NEILEGB",
    "Neil & Eureka": "NEILERKA",
    "Neil & Garwood": "NEILGAR",
    "Neil & Hill": "NEILHIL",
    "Neil & Healey": "NEILHLY",
    "Neil & Hessel": "NEILHSL",
    "Neil & Interstate": "NEILINTR",
    "Neil & Kenyon": "NEILKNYN",
    "Neil & Marketview": "NEILMKTV",
    "Neil & Marshall": "NEILMSHL",
    "Neil & North": "NEILN",
    "Neil & Springfield": "NEILSPFLD",
    "Neil & Stadium": "NEILSTDM",
    "Neil & Town Center Apt.": "NEILTCA",
    "Neil & Twins": "NEILTWN",
    "Neil & Vine": "NEILVIN",
    "Neil & Washington": "NEILWASH",
    "Neil & White": "NEILWHT",
    "Neil & Walingford": "NEILWLGFRD",
    "Napleton & Anthony": "NPLTNANTHNY",
    "Northwood & George": "NRTHWDGRG",
    "Nevada & Gregory Pl.": "NVGRGPL",
    "Nevada & Lincoln": "NVLNCLN",
    "Newport & Landis Farm": "NWPRTLNDSFRM",
    "Newport & Milford": "NWPRTMLFRD",
    "Newton & Leggett": "NWTNLGGT",
    "Newton & Nobel": "NWTNNBL",
    "Newton & Newmark": "NWTNNWMK",
    "Newton & Research": "NWTNRSRCH",
    "Oak St.": "OAK",
    "Oak & Anthony": "OAKANT",
    "Oak & Gerty": "OAKGTY",
    "Oak & Kenyon": "OAKKNYN",
    "Orchard Downs Mid-North": "ODMIDN",
    "Orchard Downs Mid-South": "ODMIDS",
    "Orchard Downs North Shelter": "ODNS",
    "Orchard Downs South Shelter": "ODSS",
    "One Illinois North": "ONENORTH",
    "One Illinois South": "ONESOUTH",
    "Pennsylvania & Fourth": "PA4TH",
    "Pennsylvania & Sixth": "PA6TH",
    "Penn & Anderson": "PAADRSN",
    "Ag. Engineering": "PAAG",
    "Penn & Broadway": "PABDWY",
    "Penn & Busey": "PABUSEY",
    "Penn & Carle": "PACARL",
    "Pennsylvania Ct.": "PACT",
    "Penn & Dorner": "PADNR",
    "Penn & Goodwin": "PAGWN",
    "Penn & Kinch": "PAKNCH",
    "Pennsylvania at Law Building": "PALAW",
    "Penn & Maryland": "PAMD",
    "Penn & Orchard": "PAORCH",
    "Pennsylvania at PAR": "PAPAR",
    "PAR": "PAR",
    "Pennsylvania & Race": "PARACE",
    "Parkview": "PARKVIEW",
    "Penn & Vine": "PAVIN",
    "Penn & Wiley": "PAWILEY",
    "Pebblebrook & Bluegrass": "PBLBRKBLGRS",
    "Pebblebrook & Rockdale": "PBLBRKRKDL",
    "Winfield Village Lot B": "PDKELOTB",
    "Winfield Village Lot G": "PDKWLOTG",
    "Winfield Village Lot M": "PDKWLOTM",
    "Krannert Art Museum": "PDYKAM",
    "Philo & Briarcliff": "PHILOBCLF",
    "Philo & Colorado": "PHILOCO",
    "Philo & Fairlawn": "PHILOFRLN",
    "Philo & Harding": "PHILOHRDG",
    "Philo & Laurel": "PHILOLRL",
    "Philo & Mumford": "PHILOMFRD",
    "Philo & Michigan": "PHILOMI",
    "Philo & Pennsylvania": "PHILOPA",
    "Philo & Scovill": "PHILOSCVL",
    "Philo & Silver": "PHILOSLVR",
    "Philo & Windsor": "PHILOWDSR",
    "Park & Central": "PKCNTRL",
    "Parkland College": "PKLN",
    "Park Lane & Bedford": "PKLNBDFD",
    "Parkland Ct. & Bradley": "PKLNCTBRAD",
    "Park Lane & Stanford": "PKLNSTFD",
    "Park & Mathews": "PKMAT",
    "Park & McCullough": "PKMCCLGH",
    "Perkins & Cherokee": "PKNSCHKE",
    "Perkins & Cooks Ln.": "PKNSCOOK",
    "Perkins & Carroll": "PKNSCROL",
    "Perkins & Eastern": "PKNSEAST",
    "Perkins & Highcross": "PKNSHICRS",
    "Perkins & Ivanhoe": "PKNSIVAN",
    "Perkins & Richard": "PKNSRICH",
    "Perkins & Raintree": "PKNSRNTRW",
    "Park & Romine": "PKRMN",
    "Park & Wright": "PKWRT",
    "Paula & Cynthia": "PLACYNTHA",
    "Paula & Garden Hills": "PLAGH",
    "Paula & Honeysuckle": "PLAHNYSKL",
    "Paula & Jeanne": "PLAJEANNE",
    "Paula & Joanne": "PLAJOANE",
    "Paula & Kirk Ln.": "PLAKIRK",
    "Paula & Larkspur": "PLALRKSPR",
    "Paula & Mattis": "PLAMATS",
    "Paula & McKinley": "PLAMCNLY",
    "Paula & Melanie": "PLAMELNE",
    "Paula & Powers": "PLAPWRS",
    "Plastipak": "PLASTIPAK",
    "Transit Plaza": "PLAZA",
    "Pomona & Bradley": "PMNABRAD",
    "Pomona & Deske Ct.": "PMNADSK",
    "Pomona & Ed Hoffman": "PMNAEH",
    "Pomona & Heritage": "PMNAHRTG",
    "Pomona & Santa Ana": "PMNASTANA",
    "Pinecrest & Porterfield": "PNCRSTPRTFLD",
    "Pinecrest & Staley": "PNCRSTSTLY",
    "Peppermill & Pebblebrook": "PPRMLPBLBRK",
    "Plant Sciences Lab": "PSL",
    "Prospect & Ayrshire Cir.": "PSPCTASRC",
    "Prospect & Ayrshire": "PSPCTASRD",
    "Prospect & Broadmoor": "PSPCTBDMR",
    "Prospect & Beardsley": "PSPCTBRD",
    "Prospect & Columbia": "PSPCTCLMBA",
    "Prospect & Dennison": "PSPCTDNSN",
    "Prospect & Devonshire": "PSPCTDVN",
    "Prospect & Eureka": "PSPCTERKA",
    "Prospect & Floral Park": "PSPCTFLRPK",
    "Prospect & Francis": "PSPCTFRAN",
    "Prospect & Francis": "PSPCTFRNS",
    "Prospect & Galen": "PSPCTGALN",
    "Prospect & Green": "PSPCTGRN",
    "Prospect & Healey": "PSPCTHEALY",
    "Prospect & Hill": "PSPCTHILL",
    "Prospect & Harvard": "PSPCTHVD",
    "Prospect & Interstate": "PSPCTINTER",
    "Prospect & John": "PSPCTJOHN",
    "Prospect & Kirby": "PSPCTKBY",
    "Prospect & Kent": "PSPCTKENT",
    "Prospect & Lincolnshire": "PSPCTLNSH",
    "Prospect at Meijer": "PSPCTMJR",
    "Prospect & Marketview": "PSPCTMKTV",
    "Prospect & Maple": "PSPCTMPL",
    "Prospect & Park Ln.": "PSPCTPKLN",
    "Prospect & Pioneer": "PSPCTPNR",
    "Prospect & Sherwood Tr.": "PSPCTSHWD",
    "Prospect & Tremont": "PSPCTTRMNT",
    "Prospect & Vine": "PSPCTVIN",
    "Prospect & Ventura": "PSPCTVTRA",
    "Prospect & Washington": "PSPCTWASH",
    "Queensway": "QNWAY1",
    "Queensway & Roland": "QNWAYRLND",
    "Race & California": "RACECA",
    "Race & Delaware": "RACEDE",
    "Race & High St.": "RACEHIGH",
    "Race & Holmes": "RACEHLMS",
    "Race & Iowa": "RACEIA",
    "Race & Illinois": "RACEIL",
    "Race & Indiana": "RACEIN",
    "Meadowbrook Park": "RACEMBRK",
    "Race & Meadow": "RACEMDW",
    "Race & McHenry": "RACEMHRY",
    "Race & Michigan": "RACEMI",
    "Race & Main": "RACEMN",
    "Race & Montclair": "RACEMTCLR",
    "Race & Mumford": "RACEMUMFRD",
    "Race & Nevada": "RACENV",
    "Race & Oregon": "RACEOR",
    "Race & Sherwin": "RACESWND",
    "Race at Stone Creek Church": "RACEUA",
    "Race & Vermont": "RACEVT",
    "Race & Washington #1": "RACEWASH1",
    "Race & Washington #2": "RACEWASH2",
    "Race & Windsor": "RACEWDSR",
    "Race & Whitehall Ct.": "RACEWTHL",
    "Round Barn & Country Fair Dr.": "RBRCFD",
    "Highcross & Kyle": "RE",
    "Restoration Urban Ministries": "RESTURBMIN",
    "Rolling Acres & Marjorie": "RLACRMRJ",
    "Roland & Aztec": "RLNDAZTEC",
    "Roland & Comanche": "RLNDCMCHE",
    "Roland & Dobbins": "RLNDDBNS",
    "Roland & Walters": "RLNDWTRS",
    "Romine & Bradley": "RMNBRAD",
    "Romine & Beardsley": "RMNBRD",
    "Romine & Eads": "RMNEADS",
    "Romine & Ellis": "RMNELLIS",
    "Romine & Eureka": "RMNERKA",
    "Romine & Tremont": "RMNTRMNT",
    "Randolph & Avondale": "RNDLFAVNDL",
    "Randolph & Bradley": "RNDLFBRAD",
    "Randolph & Beardsley": "RNDLFBRD",
    "Randolph & Charles": "RNDLFCHAS",
    "Randolph & Clark": "RNDLFCLARK",
    "Randolph & Columbia": "RNDLFCLMBA",
    "Randolph & Ells": "RNDLFELS",
    "Randolph & Eureka": "RNDLFERKA",
    "Randolph & Hill": "RNDLFHIL",
    "Randolph & Healey": "RNDLFHLY",
    "Randolph & John": "RNDLFJOHN",
    "Randolph & Maple": "RNDLFMPL",
    "Randolph & Springfield": "RNDLFSPFLD",
    "Randolph & Stanage": "RNDLFSTNAG",
    "Randolph & Tremont": "RNDLFTRMNT",
    "Randolph & University": "RNDLFUNI",
    "Randolph & Vine": "RNDLFVIN",
    "Randolph & Washington": "RNDLFWASH",
    "Randolph & White": "RNDLFWHT",
    "Randolph & William": "RNDLFWLM",
    "Research at Hobbico": "RSRCHHBCO",
    "Scottswood & Calif. Ct.": "SCWDCACT",
    "Scottswood & Illinois": "SCWDIL",
    "Scottswood & Nevada": "SCWDNV",
    "Scottswood & Oregon": "SCWDOR",
    "Springer & Country Fair Dr.": "SGRCFD",
    "Skyline & Newport": "SKYLNNWPRT",
    "Silver & Cottage Grove": "SLVRCTGRV",
    "Silver & Fletcher": "SLVRFLCHR",
    "Silver & Vawter": "SLVRVWTR",
    "Slayback & Carrie": "SLYBKCRE",
    "Slayback & Dodson West": "SLYBKDOD",
    "Slayback & Ira": "SLYBKIRA",
    "Slayback & McGee": "SLYBKMG",
    "Slayback & Smith": "SLYBKSMITH",
    "Smith & U.S. 150": "SMITH150",
    "Smith & Carrie": "SMITHCRE",
    "St. Mary's & Griffith": "SMRGRIF",
    "Smith & Rainbowview": "SMRNBVW",
    "St. Mary's & Neil": "SMRNEIL",
    "St. Mary's & Oak": "SMROAK",
    "Summersage & Switchgrass": "SMRSGSWTCHGRS",
    "Springfield at Country Fair": "SPFLD",
    "Springfield & Birch": "SPFLDBRCH",
    "Springfield & Busey": "SPFLDBSY",
    "Springfield & Country Fair Dr.": "SPFLDCFD",
    "Springfield & Chicago": "SPFLDCHI",
    "Springfield & Duncan": "SPFLDDNCN",
    "Springfield & Draper": "SPFLDDRPR",
    "Springfield & Edwin": "SPFLDEDWN",
    "Springfield & Elm": "SPFLDELM",
    "Springfield & Fair": "SPFLDFAIR",
    "Springfield & Fieldstone": "SPFLDFLDSTN",
    "Springfield & Garfield": "SPFLDGRFLD",
    "Springfield & Gregory St.": "SPFLDGRGST",
    "Springfield & Highland": "SPFLDHILND",
    "Springfield & Harvey": "SPFLDHVY",
    "Springfield & James": "SPFLDJAS",
    "Springfield & Kenwood": "SPFLDKNWD",
    "Springfield & Lynn": "SPFLDLYN",
    "Springfield & Mattis": "SPFLDMATS",
    "Springfield & McKinley": "SPFLDMCNLY",
    "Springfield & New": "SPFLDNEW",
    "Springfield & Pine": "SPFLDPINE",
    "Springfield at Phillips Rec. Ctr": "SPFLDPRC",
    "Springfield & Prairie": "SPFLDPRRE",
    "Springfield & Prospect": "SPFLDPSPCT",
    "Springfield & Ridgeway": "SPFLDRGWY",
    "Springfield & Russell": "SPFLDRSL",
    "Springfield & Royal Ct.": "SPFLDRYLCT",
    "Springfield & Staley": "SPFLDSTLY",
    "Springfield & VanDoren": "SPFLDVNDRN",
    "Springfield & Willis": "SPFLDWLS",
    "Springfield & Westlawn": "SPFLDWLWN",
    "Springhill & Glenhill": "SPGHLGLNHL",
    "Susan Stone & Galena": "SSTNGLNA",
    "Susan Stone & Jane Ann Ct.": "SSTNJACT",
    "Susan Stone & Jane Lee Ct.": "SSTNJACT",
    "Susan Stone & Moss": "SSTNMOS",
    "Susan Stone & Myra Ridge": "SSTNMYRA",
    "Susan Stone & Plains Ct.": "SSTNPLN",
    "Susan Stone & Summit": "SSTNSMT",
    "Sussex & Oakmont": "SSXOKMNT",
    "Sussex & Southfield": "SSXSFLD",
    "Sussex & Windward": "SSXWIND",
    "Sussex & Waterford": "SSXWTRFD",
    "Stadium & Oak": "STDMOAK",
    "State & Avondale": "STEAVNDL",
    "State & Birch": "STEBRCH",
    "State & Beardsley": "STEBRD",
    "State & Buena Vista": "STEBV",
    "State & Cedar": "STECDR",
    "State & Charles": "STECHAS",
    "State & Clark": "STECLARK",
    "State & Columbia": "STECLMBA",
    "State & Ells": "STEELS",
    "State & Eureka": "STEERKA",
    "State & Hill": "STEHIL",
    "State & Healey": "STEHLY",
    "State & Hessel": "STEHSL",
    "State & John": "STEJOHN",
    "State & Maple": "STEMPL",
    "State & Park": "STEPK",
    "State & Springfield": "STESPFLD",
    "State & Stanage": "STESTNAG",
    "State & Trade Center Dr.": "STETC",
    "State & Tremont": "STETRMNT",
    "State & University": "STEUNI",
    "State & Vine": "STEVIN",
    "State & Washington": "STEWASH",
    "State & White": "STEWHT",
    "State & William": "STEWLM",
    "Staley & Amherst": "STLYAMHT",
    "Staley & Clubhouse": "STLYCLBHS",
    "Staley & Colleen": "STLYCLEEN",
    "Staley & Copper Ridge": "STLYCPRRDG",
    "Staley & Inverness": "STLYINV",
    "Staley & Kirby": "STLYKBY",
    "Staley & Kearns": "STLYKRNS",
    "Staley & Turnberry": "STLYTRNBRY",
    "St. Mathews": "STMAT",
    "Stone Creek & Bohn": "STNCRKBN",
    "Stone Creek & Stillwater Landing": "STNCRKSTLWTR",
    "Stone Creek & Venturi": "STNCRKVNTRI",
    "Colorado at Steer Place": "STP",
    "Sunnycrest": "SUNNYCREST",
    "Savoy Walmart": "SWALMART",
    "Sherwin & Pond Ridge": "SWNDPNDR",
    "Sherwin & Persimmon": "SWNDPSMN",
    "Sherwin & Sherwin Cir.": "SWNDSWNC",
    "Sherwin & Sherwin Cir 2": "SWNDSWNC2",
    "Sherwin & Yankee Ridge": "SWNDYNKR",
    "Switchgrass & Trailway": "SWTCHGRSTRLWY",
    "Switchgrass & Wildflower": "SWTCHGRSWLDFLWR",
    "Tatman Ct. & Highcross": "TAT130",
    "Town & Country Apts.": "TCA",
    "Town Center at Meijer": "TCBMJR",
    "Town Center & Menards": "TCBMNRDS",
    "Town Center & Moreland": "TCBMRLND",
    "Town Center & Neil": "TCBNEIL",
    "Town Center & Prospect": "TCBPSPCT",
    "Town Center at Target": "TCBTGT",
    "Toalson & Interstate": "TLSNINTER",
    "Timbergate & Cherry Hills": "TMGTCHHL",
    "Thompson Park": "TMPSNPK",
    "Trails & Baronry": "TRLSBRN",
    "Trails & Chatham": "TRLSCHAT",
    "Trails & Fawn Hill": "TRLSFWN",
    "Trails & Philo": "TRLSPHILO",
    "Urbana High School": "UHS",
    "U of I Credit Union": "UICU",
    "Urbana Middle School": "UMS",
    "University & Second": "UNI2ND",
    "University & Fourth": "UNI4TH",
    "University & Sixth": "UNI6TH",
    "University & Ash": "UNIASH",
    "University & Central": "UNICENT",
    "University & Cottage Grove": "UNICTGRV",
    "University & Draper": "UNIDRPR",
    "University & Elm": "UNIELM",
    "University & Fair": "UNIFAIR",
    "University & Goodwin": "UNIGWN",
    "University & Hickory": "UNIHKRY",
    "University & Harvey": "UNIHVY",
    "University & James": "UNIJAS",
    "University & Lake": "UNILAKE",
    "University & Lierman": "UNILRMN",
    "University & Lynn": "UNILYN",
    "University & Mattis": "UNIMATS",
    "University & McCullough": "UNIMCLGH",
    "University & McKinley": "UNIMCNLY",
    "University & Maple": "UNIMPL",
    "University & Neil": "UNINEIL",
    "University & New": "UNINEW",
    "University & Prairie": "UNIPRRE",
    "University & Prospect": "UNIPSPCT",
    "University & Race": "UNIRACE",
    "University & Randolph": "UNIRNDLF",
    "University & Russell": "UNIRSL",
    "University & Sabin": "UNISBN",
    "University & Sycamore": "UNISCMR",
    "": "UNITD4140	University at MTD",
    "University & Victor": "UNIVCTR",
    "University & Vine": "UNIVIN",
    "University & Willis": "UNIWLS",
    "University & Wright": "UNIWRT",
    "Urbana Meijer": "URBMEIJ",
    "Urbana Walmart": "UWALMART",
    "Vet-Med": "VETMED",
    "Vine & Burkwood Ct.": "VINBKWD",
    "Vine & Brookens": "VINBRKNS",
    "Vine & California": "VINCA",
    "Vine & Colorado": "VINCO",
    "Vine & Evergreen Ct.": "VINEGRN",
    "Vine & Elm": "VINELM",
    "Vine & Michigan": "VINEMI",
    "Vine & Fairlawn": "VINFRLN",
    "Vine & George Huff": "VINGHF",
    "Vine & Green": "VINGRN",
    "Vine & Holmes": "VINHLMS",
    "Vine & Harris": "VINHRIS",
    "Vine & Illinois": "VINIL",
    "Vine & Lynn": "VINLYN",
    "Vine & McKinley": "VINMCNLY",
    "Vine & Mumford": "VINMFRD",
    "Vine & McHenry": "VINMHRY",
    "Vine & Montclair": "VINMNTCLR",
    "Vine & Nevada": "VINNV",
    "Vine & Oregon": "VINOR",
    "Vine & Pell Cir.": "VINPELL",
    "Vine & Prairie": "VINPRRE",
    "Vine & Scovill": "VINSCVL",
    "Vine & Sunnycrest": "VINSNYC",
    "Vine & Shurts": "VINSRTS",
    "Vine & Washington": "VINWASH",
    "Vine & Willis": "VINWLS",
    "Vine & Water": "VINWTR",
    "Viking North": "VKINGN",
    "Viking South": "VKINGS",
    "Valerie & Alpine": "VLRALPN",
    "Valerie & Meaghan": "VLRMGHN",
    "Vance & Napleton": "VNCENPLTN",
    "Vermont & Kinch": "VTKNCH",
    "Champaign Walmart": "WALMART",
    "Washington & Second": "WASH2ND",
    "Washington & Third": "WASH3RD",
    "Washington & Fourth": "WASH4TH",
    "Washington & Ash": "WASHASH",
    "Washington & Broadway": "WASHBDWY",
    "Washington & Country Squire": "WASHCSQR",
    "Washington & Hickory": "WASHHKRY",
    "Washington & Kinch": "WASHKNCH",
    "Washington & Lanore": "WASHLNR",
    "Washington & Lierman": "WASHLRMN",
    "Washington & MacArthur": "WASHMCRTR",
    "Washington & Phillips": "WASHPHLPS",
    "Washington & Rainbow View": "WASHRAIN",
    "Washington School": "WASHSCL",
    "Washington & Scottswood": "WASHSCWD",
    "Washington & Smith": "WASHSMITH",
    "Washington & Timothy Tr.": "WASHTIM",
    "Woodfield & Arbor Town": "WDFLDABT",
    "Woodfield & Curtis": "WDFLDCTS",
    "Wedgewood & Timbergate": "WDGWDTMGT",
    "Windsor Rd.": "WDSR",
    "Windsor & Bel Air": "WDSRBA",
    "Windsor & Brookshire": "WDSRBKSR",
    "Windsor & Boulder": "WDSRBLDR",
    "Christie Clinic": "WDSRCCS",
    "Windsor & Cherry Hills": "WDSRCHHL",
    "Windsor & Carlisle": "WDSRCLSL",
    "Clark Lindsey Village": "WDSRCLV",
    "Windsor & Crossing Ct.": "WDSRCRSNG",
    "Windsor & Donnybrook": "WDSRDNBK",
    "Windsor & Duncan": "WDSRDNCN",
    "Windsor & Phinney": "WDSRFNY",
    "Windsor & Imperial": "WDSRIMP",
    "Windsor & Jordan": "WDSRJDN",
    "Windsor & Lakewood": "WDSRLKWD",
    "Windsor & Lynn": "WDSRLYN",
    "Windsor & Melrose": "WDSRMLRS",
    "Windsor & Monterey": "WDSRMTRY",
    "Windsor & Morrissey Park": "WDSRMYPK",
    "Windsor & Myra Ridge": "WDSRMYRA",
    "Windsor & Prospect": "WDSRPSPCT",
    "Windsor & Scottsdale": "WDSRSCTDL",
    "Windsor & Susan Stone": "WDSRSSTN",
    "Windsor & Stillwater": "WDSRSTLW",
    "Windsor & Vine": "WDSRVIN",
    "Windsor & Village Green": "WDSRVLGGRN",
    "Windsor & Valleybrook": "WDSRVYBK",
    "Windsor West Apts": "WDSRWEST",
    "Windsor & Windward": "WDSRWIND",
    "Windsor & Winchester": "WDSRWNCH",
    "Windsor & Willowbrook": "WDSRWWBK",
    "Westgate Apts.": "WESTGATE",
    "White & First": "WHT1ST",
    "White & Second": "WHT2ND",
    "White & Fourth": "WHT4TH",
    "White & Sixth": "WHT6TH",
    "White & Wright": "WHTWRT",
    "Willow & Baker": "WILLOWBKR",
    "Willow & Kenyon": "WILLOWKNYN",
    "Windward & Autumnwood": "WINDATMWD",
    "Windward & Countryside": "WINDCNTYSD",
    "Windward Point": "WINDPT",
    "Windward & Waterford": "WINDWTRFD",
    "Wildflower & Chickory": "WLDFLRCKRY",
    "Wildflower & Trailway": "WLDFLRTRLWY",
    "Willow & Beason": "WLLWBESN",
    "William & Bellepark": "WLMBLPRK",
    "William & Centennial": "WLMCENT",
    "William & Dogwood": "WLMDGWD",
    "William & Duncan": "WLMDNCN",
    "William & Goldenview": "WLMGLDVW",
    "William & Kenwood": "WLMKNWD",
    "William & Maplepark": "WLMMPLPK",
    "William & Oakcrest": "WLMOKCRST",
    "William & Stratford": "WLMSTFRD",
    "Walnut & Columbia": "WLNTCLMBA",
    "Walnut & Logan": "WLNTLGN",
    "Walnut & University": "WLNTUNI",
    "Walnut & Washington": "WLNTWASH",
    "Bradley at WLRW": "WLRW",
    "Williamsburg": "WMBG",
    "Williamsburg & Garden Hills": "WMBGGH",
    "Williamsburg & Mattis": "WMBGMATS",
    "Williamsburg & Summerlin": "WMBGSMLN",
    "Williamsburg & Summit Ridge": "WMBGSTRG",
    "Williamsburg & Thornton": "WMBGTRNTN",
    "Williamsburg & Winston": "WMBGWNTN",
    "Winchester & Aspen": "WNCHASP",
    "Winchester & Broadmoor": "WNCHBDMR",
    "Winchester & Brookhaven": "WNCHBKHVN",
    "Winchester & Blackthorn": "WNCHBKTRN",
    "Winchester & Belmore": "WNCHBLMR",
    "Winchester & Barberry": "WNCHBRBY",
    "Winchester & Branch": "WNCHBRCH",
    "Winchester & Cypress": "WNCHCYPS",
    "Winchester & Glenoak": "WNCHGLNK",
    "Winchester & Sumac": "WNCHSMC",
    "Winchester & Southmoor": "WNCHSMR",
    "Winchester & Tamarack": "WNCHTMRK",
    "Windsor & Fields South": "WNDSRFLDS",
    "Windsor & Mullikin": "WNDSRMLKN",
    "Windsor & Staley": "WNDSRSTLY",
    "Wendover & Country Bend": "WNDVRCTRYBND",
    "Wendover & Pebble Creek": "WNDVRPBLCK",
    "Wendover & Summerview": "WNDVRSMRVW",
    "Wendover & Woodspring": "WNDVRWDSPG",
    "Ward & Kerr": "WRDKER",
    "Wright & Beech": "WRTBCH",
    "Wright & Beslin": "WRTBSLN",
    "Wright & Chalmers": "WRTCHAL",
    "Wright & Church": "WRTCHCH",
    "Wright & Columbia": "WRTCLMBA",
    "Wright & Dublin": "WRTDBLN",
    "Wright & Hill": "WRTHIL",
    "Wright & Healey": "WRTHLY",
    "Wright & Springfield": "WRTSPFLD",
    "Wright & Stoughton": "WRTSTOTN",
    "Wright & Washington": "WRTWASH",
    "Westfield & Alton": "WSFLDALTN",
    "Westfield & Carrelton": "WSFLDCRLTN",
    "Westfield & Lawndale": "WSFLDLWNDL",
    "Westfield & Sangamon": "WSFLDSANG",
    "Westfield & Sheridan": "WSFLDSRDN",
    "Westfield & William": "WSFLDWLM",
    "Stephens Family YMCA": "YMCA"
}
